### ISSUE TITLE
beastiebox(bsd license)  has few commands which are not yet in toybox. Why not merge those parts into toybox

### ISSUE THREAD

**Issue by zaxebo1** [landley/toybox#10]
[1]  http://beastiebox.sourceforge.net/ is another attempt which tries to be port some utilities of busybox. I think it has few commands implemented which are not in toybox, **may be toybox can benefit by getting it integrated into toybox**

```
fsck,fsck_ffs, ps, [, ping (fully implemented), less,more,sysctl,pfctl,wiconfig,traceroute(fully implemented) ,stty,reboot,halt,poweroff,ex,vi,fdisk,disklabel,tar,getty
```

these above ^ commands are in http://beastiebox.sourceforge.net/ (BSD licensed alternative of busybox), which are probably not (or not fully implemented)  in toybox. So,we can probably merge it into toybox.

**Comment by landley** [comment]
1) http://landley.net/toybox/roadmap.html#beastiebox

2) http://lists.busybox.net/pipermail/busybox/2005-November/051179.html
