### ISSUE TITLE
install -d -o USER -g GROUP DEST doesn't set uid/gid

### ISSUE THREAD

**Issue by medvid** [landley/toybox#105]
"install -d" doesn't honor custom uid/gid.
install_main returns early if (flags & FLAG_d), doing mkpathat without fchown.

**Comment by enh-google** [comment]
> When calling **lchown**() it does xgetuid() and xgetgid() for the default values
> you're not overriding (when you have -o or -g but not both). Technically that
> should be the fsuid, but although there's a setfsuid() I can't find a _getfsuid()_?

i'm not sure i understand this? seems like you're using -1 and letting it be the kernel's problem, so there's nothing left to do here?
```
  TT.uid = TT.i.o ? xgetuid(TT.i.o) : -1;
  TT.gid = TT.i.g ? xgetgid(TT.i.g) : -1;
...
        if (lchown(*ss, TT.uid, TT.gid)) perror_msg("chown '%s'", *ss);
```

**Comment by enh-google** [comment]
@medvid --- do you have a test case that still doesn't work with current toybox? (i'll reopen if you just comment here. no need for a new bug.) otherwise, i think this was fixed years ago..
