### ISSUE TITLE
array out of bounds error (buffer overrun for read)

### ISSUE THREAD

**Issue by mlite** [landley/toybox#106]
The static array declared at conf.c::35 is (negative) overran at conf.c::393

DTS_MSG: Stensal C/C++ DTS detected a fatal program error!
DTS_MSG: Continuing the execution will cause unexpected behaviors, abort!
DTS_MSG: Reading 1 bytes at 0x81aa1e3 will read undefined values.
DTS_MSG: Diagnostic information:
- The object to-be-read (start:0x81aa1e4, size:128 bytes) is allocated at
-     file:/home/sbuilder/workspace/toybox/kconfig/conf.c::
-                               0x81aa1e4               0x81aa263
-                               +------------------------+
-                         ......| the object  to-be-read |
-                               +------------------------+
-                            ^~~~~~~~~~
-   the read starts at 0x81aa1e3 that is 1 bytes before the object start.
- Stack trace (most recent call first):
-[1]  file:/home/sbuilder/workspace/toybox/kconfig/conf.c::393, 12
-[2]  file:/home/sbuilder/workspace/toybox/kconfig/conf.c::444, 3
-[3]  file:/home/sbuilder/workspace/toybox/kconfig/conf.c::465, 3
-[4]  file:/home/sbuilder/workspace/toybox/kconfig/conf.c::465, 3
-[5]  file:/home/sbuilder/workspace/toybox/kconfig/conf.c::598, 3

**Comment by landley** [comment]
That's the kconfig infrastructure copied from Linux 2.6.12.  The kconfig/README file explains the todo item to rewrite it all from scratch (for license reasons). The binay it produces doesn't ship: it runs during the build to implement "make menuconfig", and everything else it does basically converts one text file format to another (Config.in to .config) during the build.
