### ISSUE TITLE
cp segfault with empty list in --preserve

### ISSUE THREAD

**Issue by BookGin** [landley/toybox#108]
## Description
When specify `--preserve` without providing a list, `cp` will segfault.

```sh
$ cp --preserve foo bar
[1]    16649 segmentation fault (core dumped)  /tmp/toybox/bin/cp --preserve foo bar
```

The root cause is `xstrdup(TT.c.preserve)`, because `TT.c.preserve` is NULL here. 

https://github.com/landley/toybox/blob/master/toys/posix/cp.c#L378

## Version

```sh
$ cp --version
toybox android-wear-8.0.0_r2-1-gb5744abfe599
```

**Comment by landley** [comment]
Fixed in commit d4017dbd0a42. Thanks for the heads up.
