### ISSUE TITLE
./configure option to embed zsh (MIT licensed) into toybox

### ISSUE THREAD

**Issue by zaxebo1** [landley/toybox#11]
There can be a optional ./configure option in toybox - to point to source code location of zsh ; so that one can embed compile "zsh too into toybox"  (zsh is a **full implementation of bash**, but MIT licensed)

note that you are not actually putting zsh source code of zsh into toybox. you are just letting people an option to embed an external source code tree into toybox, so that they can get "applet" of zsh embedded into single binary of "toybox"

**Comment by jbergstroem** [comment]
I personally feel this is outside of the scope that toybox tries to accomplish. What's the benefit of baking this into toybox when you just as easily can distribute it on the side?

**Comment by technosaurus** [comment]
Something that may be in scope would be to support building in external utilities.  IIRC you can just add a build folder.  It wouldn't be a huge stretch to create a separate project(s) for out of scope projects similar to gstreamer's bad and ugly plugins, but for permissive licensed and gpl-ish licensed programs.  They could be added at build time via git submodules.

**Comment by tpimh** [comment]
zsh is very large and complicated, while toybox tries to stay as small and simple as possible. So I don't think this would be ever implemented.
What is the problem with having zsh as a separate binary?

**Comment by landley** [comment]
Toybox isn't MIT licensed (one of the many, many public domain adjacent licenses which require you to copy a specific blob of text into all derived works), it's 0BSD which is public domain equivalent (does not require you to copy specific text into derived works, interchangeable with other public domain equivalent licenses like CC0, The Unlicense, WTFPL, and the John The Ripper license).
