### ISSUE TITLE
0.8.0 github release identifies as 0.78

### ISSUE THREAD

**Issue by ryanwoodsmall** [landley/toybox#114]
Built toybox from GitHub release archive and noticed it was still identifying as 0.7.8. Looks like only a single line difference between landley.net and github.com release archive:

```
diff -Naur toybox-0.8.0-github/main.c toybox-0.8.0-landley/main.c
--- toybox-0.8.0-github/main.c  2019-02-09 01:54:47.000000000 +0000
+++ toybox-0.8.0-landley/main.c 2019-02-09 02:15:28.000000000 +0000
@@ -9,7 +9,7 @@
 #ifndef TOYBOX_VENDOR
 #define TOYBOX_VENDOR ""
 #endif
-#define TOYBOX_VERSION "0.7.8"TOYBOX_VENDOR
+#define TOYBOX_VERSION "0.8.0"TOYBOX_VENDOR
 #endif
 
 // Populate toy_list[].
```

**Comment by landley** [comment]
http://lists.landley.net/pipermail/toybox-landley.net/2019-February/010143.html

https://github.com/landley/toybox/commit/b11e1206b4193dd46b4c40c333175fceadd409df

**Comment by ryanwoodsmall** [comment]
Ah! Thanks Rob. Sorry I missed those.
