### ISSUE TITLE
mv does not preserve file creation date when moving between directories in different mount points

### ISSUE THREAD

**Issue by atilamtm** [landley/toybox#123]
Would be nice to have 'mv' keep the file creation date when moving files between different mount points/storages.
When moving from Android's internal storage to external SD card, the creation date is updated to the current date. This messes up apps that use the file creation date to order its files, such as Google Photos: https://productforums.google.com/forum/#!topic/photos/pIKjEkYbmaQ

montana:/storage/4421-0568/tmp # ls -la /storage/self/primary/tmp/                                                                                                                                                                                     
total 24
drwxrwx--x  2 root sdcard_rw 4096 2019-03-14 16:54 .
drwxrwx--x 25 root sdcard_rw 4096 2019-03-08 10:17 ..
-rw-rw----  1 root sdcard_rw    0 2019-03-14 16:54 test1
-rw-rw----  1 root sdcard_rw    0 2019-03-14 16:54 test2
montana:/storage/4421-0568/tmp # mv /storage/self/primary/tmp/test1 .                                                                                                                                                                                  
montana:/storage/4421-0568/tmp # mv /storage/self/primary/tmp/test2 .                                                                                                                                                                                  
montana:/storage/4421-0568/tmp # ls -la
total 64
drwxrwx--x  2 root sdcard_rw 32768 2019-03-14 16:58 .
drwxrwx--x 13 root sdcard_rw 32768 2019-03-14 16:58 ..
-rwxrwx--x  1 root sdcard_rw     0 2019-03-14 16:58 test1
-rwxrwx--x  1 root sdcard_rw     0 2019-03-14 16:58 test2

**Comment by landley** [comment]
Hmmm, mv should enable --preserve=all so that's a bug...

**Comment by atilamtm** [comment]
Hi Landley, it does keep the timestamps when moving within the same partition, the issue only happens when moving between different partitions.

**Comment by landley** [comment]
Try commit ec3e49c93b07

**Comment by landley** [comment]
In the absence of a response, I'm going to assume that fixed it.
