### ISSUE TITLE
Grep results incorrect

### ISSUE THREAD

**Issue by E5ten** [landley/toybox#126]
Sorry for the really large example list here, but it's what arch's `makepkg` is running to produce the error, basically using grep to compare 2 bash arrays, but I had to get the values it was using from bash -x output so I could have a test, basically toybox grep outputs bbswitch-dkms as if it isn't in the first list of strings to inverse match against. The actual command had a much larger list of package in the 2 arrays, although both arrays were still identical, and it also had more strings in the output, I could put that very long thing here or in a pastebin of some kind if you want.
```
toybox grep -Fxvf <(printf '%s\n' alacritty-git alsa-lib alsa-utils alsa-utils-openrc arch-install-scripts archlinux-mirrorlist aria2 artix-mirrorlist artix-sysvcompat artools-base asp auracle-git aurutils-git avidemux-cli avidemux-qt bash bash-completion bat-cat-git bbswitch-dkms bc binutils boost-libs breeze breeze-icons busybox-git byacc bzip2 c-ares ca-certificates ca-certificates-mozilla ca-certificates-utils cairo ccache checkbashisms chromium-widevine cmake cppcheck cracklib cronie cronie-openrc curl dash dateutils dbus dbus-openrc deb2appimage desktop-file-utils dhcpcd dhcpcd-openrc dialog diffutils discord-rpc-api-git dkms dmenu dnssec-anchors) <(printf '%s\n' alacritty-git alsa-lib alsa-utils alsa-utils-openrc arch-install-scripts archlinux-mirrorlist aria2 artix-mirrorlist artix-sysvcompat artools-base asp auracle-git aurutils-git avidemux-cli avidemux-qt bash bash-completion bat-cat-git bbswitch-dkms bc binutils boost-libs breeze breeze-icons busybox-git byacc bzip2 c-ares ca-certificates ca-certificates-mozilla ca-certificates-utils cairo ccache checkbashisms chromium-widevine cmake cppcheck cracklib cronie cronie-openrc curl dash dateutils dbus dbus-openrc deb2appimage desktop-file-utils dhcpcd dhcpcd-openrc dialog diffutils discord-rpc-api-git dkms dmenu dnssec-anchors)
bbswitch-dkms
```
Sorry for the lack of specificity with what's going wrong but I really don't have any clue how to describe this in a better way than the match not happening correctly. Maybe something to do with the length? No real basis but the amount of outputed lines does increase quite a bit as the arrays did so maybe that's it.

EDIT: Sorry I forgot to mention this succeeds with busybox grep and GNU grep.

**Comment by landley** [comment]
Fixed in commit a39eab3fc7da
