### ISSUE TITLE
grep errors when + is used before regex

### ISSUE THREAD

**Issue by E5ten** [landley/toybox#127]
`grep -E +[0-9]` errors with `grep: bad REGEX '+[0-9]': Invalid preceding regular expression` while GNU and busybox grep accept that and match accordingly.

**Comment by enh** [comment]
What C library did you build with? (That's probably the difference here.)

**Comment by enh** [comment]
actually, no:

```
# glibc
grep: bad REGEX '+[0-9]': Invalid preceding regular expression
```

```
# Android's bionic (and other BSDs):
grep: bad REGEX '+[0-9]': repetition-operator operand invalid
```

looks like glibc's `<regex.h>` has some extra stuff, specifically a `RE_SYNTAX_EGREP`. glibc appears to be the only libc that supports this.

(this also means that BSD grep rejects your example with roughly the same error message.)

**Comment by E5ten** [comment]
Would it be possible for toybox to detect which libc it was being built against and enable RE_SYNTAX_EGREP if it's using glibc?

**Comment by landley** [comment]
That's the sort of thing lib/portability.h and lib/portability.c are for. That said, different behavior from different libc's is generally a downside?

**Comment by E5ten** [comment]
I was unsure earlier but I'm definitely in agreement now, that would be a downside.
