### ISSUE TITLE
Replacement for standard C API: system

### ISSUE THREAD

**Issue by pocomane** [landley/toybox#129]
I compiled lua as a toybox toy. Now I want to replace the lua call to the `system` C API with a function that uses the toybox internal shell (i.e. sh, that I enabled in the .config). Is there a such replacement function? I tryed with the following one:

```
int toybox_system_replacement( char * run ){
  struct toy_context temp;
  memcpy(&temp, &toys, sizeof(struct toy_context));
  memset(&toys, 0, sizeof(struct toy_context));
  sigjmp_buf rebound;
  struct toy_list *tl = toy_find("sh");
  if (!sigsetjmp(rebound, 1)) {
    toys.rebound = &rebound;
    char *cmd[4];
    cmd[0] = "sh";
    cmd[1] = "-c";
    cmd[2] = run;
    cmd[3] = NULL;
    toy_init(tl, cmd);
    printf("DEBUG [%s]\n",run);
    tl->toy_main();
  }
  int exitval = toys.exitval;
  if (toys.optargs != toys.argv+1) free(toys.optargs);
  if (toys.old_umask) umask(toys.old_umask);
  memcpy(&toys, &temp, sizeof(struct toy_context));
  return exitval;
}
```

but it does not work. For example, 

```
toybox lua -e 'print(os.execute[[acpi]])'
```

gives:

```
DEBUG [acpi]
sh: exec acpi: No such file or directory
```

(while `toybox sh -c acpi` gives something like `Battery 0: 96%`)

**Comment by landley** [comment]
You might be looking for the function toy_exec() in main.c at the top level, something like:

char *cmd[] = {"sh",  "-c" "echo hello", 0};
toy_exec(cmd);

Or you might want lib/xarg.s functions xrun() (which launches a child process and waits for it to finish with the same stdin/stdout), or one of the xpopen() variants (which are like popen() but use vfork instead of fork, and xexec() instead of exec so they'll call the built-in version and fall back to an external version if there's no builtin or we've eaten too much stack and should exec to get a fresh stack.)

There's also a static function in toys/*/mount.c called tortoise() that shells out to a child program and captures its output as a return string (or NULL if it couldn't run it). I haven't genericized that into lib/ yet because there wasn't a second command using it, but if you like I could do that. (Maybe a more appropriate name is shellout() ?)

Unfortunately the toys/pending/sh.c that's checked in at the moment is basically a stub, and doesn't even implement environment variable support or control statements (if, while, etc). I'm working on it now and hope to have something better checked in over the coming week.

**Comment by pocomane** [comment]
I do not want to start a child process, so I tried with the toy_exec. However I still have the same problem.

The situation can be summarized by:
- I added a toy
- I launch toybox calling my new toy
- The new toy needs at a chertain point to call the `sh` toy without fork

If I call `sh` with

```
void toybox_shell( char * run ){
  char *cmd[] = {"sh","-c",run,0};
  printf("DEBUG [%s]\n",run);
  toy_exec(cmd);
}
```

I got a segfault. I suppose it is because of the global context being populated by the call to the new toy. So I changed it to


```
void toybox_shell( char * run ){
  struct toy_context temp;
  memcpy(&temp, &toys, sizeof(struct toy_context));
  memset(&toys, 0, sizeof(struct toy_context));
  char *cmd[] = {"sh","-c",run,0};
  printf("DEBUG [%s]\n",run);
  toy_exec(cmd);
  memcpy(&toys, &temp, sizeof(struct toy_context));
}
```

but then I got

```
DEBUG [acpi]
sh: exec acpi: No such file or directory
```

as before.

To be clear, I have no 'acpi' command installed in my system. I want `sh` to call the toybox internal one. I.e. the same I got when I call `toybox sh -c acpi`.

I know `sh` is still "Pending", however for now I just need it to call simple commands, with a pipe/redirect at most. I am planning to using this system in some minimal docker image, where the most of the work will be done by a lua script. The toybox is needed as a quick way to get some functionality that is not in the plain lua interpreter (e.g. filesystem listing). Right now I am doing this using the standard toybox and an external lua binary. But I would like to merge all in a single binary so that I do not need any external configuration (e.g. to put `toybox sh` as system shell, etc).

**Comment by landley** [comment]
toy_exec() shouldn't return, it calls xexit() at the end. It calls toy_init() which does the memsets for you already. You shouldn't be having a segfault, it sounds like your global state isn't set up right in the lua command?

toy_exec() called the internal "sh", the one I said is just a stub. The error message "sh: exec acpi" starts with "sh:" because it's sh complaining.

Could you post what you've done already somewhere so I could see what you're actually doing? It's hard to debug in the abstract.

**Comment by pocomane** [comment]
If toy_exec does not return, It is not the solution I was searching for. I do not know if it is possible, but I just want a function to replace the C `system`, and such that it can be called multiple times during the process execution (so it must return). The `system` replacement should use the toybox shell.

I did not post my code before just because it involves lua. However, it is a very minimal toy:

```
/* lua.c - Wrap the PUC-Rio lua VM

USE_LUA(NEWTOY(lua, NULL, TOYFLAG_USR|TOYFLAG_BIN))

config LUA
  bool "lua"
  default y
  help
    usage: lua [options] [script [args]]

    lua VM.

    Available options are:
      -e stat  execute string 'stat'
      -i       enter interactive mode after executing 'script'
      -l name  require library 'name' into global 'name'
      -v       show version information
      -E       ignore environment variables
      --       stop handling options
      -        stop handling options and execute stdin
*/

#define FOR_lua
#include "toys.h"

GLOBALS(
  long w;

  unsigned total;
)

// Make sure to rename the lua.c main() function to:
int lua_main_low( int argc, char *argv[] );

int toybox_execute( char * run ){
  struct toy_context temp;
  memcpy(&temp, &toys, sizeof(struct toy_context));
  memset(&toys, 0, sizeof(struct toy_context));
  char *cmd[] = {"sh","-c",run,0};
  printf("DEBUG [%s]\n",run);
  toy_exec(cmd);
  memcpy(&toys, &temp, sizeof(struct toy_context));
  return 0;
}

void lua_main (void) {
  int argc;
  for (argc = 0; toys.argv[argc] != NULL; argc++ );
  lua_main_low( argc, toys.argv );
}
```

While in the lua source:
- The `main` has been renamed to `lua_main_low`
- The call to `system` in loslib.c has been replaced with a call to `toybox_execute` (passed arguments are not changed)

A lua script reaches the call in loslib.c every time the lua function `os.execute` is called. With the `system` replacement I hope to call the toybox internal shell instead of the OS one. It would be nice if it does not fork, but if it needs to, I can live with that.

Making a long story short, I think I can summaryze my question in: How I have to execute the command `cmd` in the following toy

```
/* test_case.c

USE_TEST_CASE(NEWTOY(lua, NULL, TOYFLAG_USR|TOYFLAG_BIN))

config TEST_CASE
  bool "test_case"
  default y
  help
    usage: test_case
*/

#define FOR_test_case
#include "toys.h"

GLOBALS(
  long w;
  unsigned total;
)

int toybox_execute( char * run ){
  struct toy_context temp;
  memcpy(&temp, &toys, sizeof(struct toy_context));
  memset(&toys, 0, sizeof(struct toy_context));
  char *cmd[] = {"sh","-c",run,0};

  toy_exec(cmd); // <-- ???

  memcpy(&toys, &temp, sizeof(struct toy_context));
  return 0;
}

void test_case_main (void) {
  toybox_execute( "uuidgen" );
  toybox_execute( "uuidgen" );
}
```

such that `./toybox test_case` will print two random uuid using the internal `uuidgen` toy?

Currently it calls `sh` one time with the arguments `-c` and `uuidgen`, then it search for an OS command named `uuidgen` (that I have not in my OS). With the code in the OP, `sh` is correctly called two times, but it still fails to use the internal `uuidgen`. Note:
- `./toybox uuidgen` writes a random uuid, so the toy is correctly compiled
- `./toybox sh -c uuidgen` writes a random uuid using the internal toy

**Comment by pocomane** [comment]
I found some time to investigate on the first issue, i.e. why it calls the system wide command instead of the toy.

What happen is the following:
- My test toy calls the sh toy with "-c" and "uuidgen"
- Sh find the "uuidgen" in the toy list
- The toy has the TOYFLAG_NOFORK flag UNSET so the branch at sh.c:165 is skipped and the one at sh.c:182 is execute
- The sh.c:182 DOES NOT run the toy but it tryes to execute a system command "uuidgen" (also if a toy with the same name was found)

The last point seems wrong to me, since it introduce an inconsistence, not in the how the process is run (fork vs no-fork) but in WHICH process is run.

In the case this is the wanted behaviour, is there any compilation time flag that enables an "Always try the toy first" mode? If not, what do you think about adding it? Maybe something like the following:

```
/ Execute the commands in a pipeline
static void run_command(struct sh_process *pp)
{
  struct toy_list *tl = toy_find(*pp->arg.v);

  // Is this command a builtin that should run in this process?
  if (tl && (tl->flags & TOYFLAG_NOFORK)) {
    struct toy_context temp;
    sigjmp_buf rebound;

    // This fakes lots of what toybox_main() does.
    memcpy(&temp, &toys, sizeof(struct toy_context));
    memset(&toys, 0, sizeof(struct toy_context));

    if (!sigsetjmp(rebound, 1)) {
      toys.rebound = &rebound;
      toy_init(tl, pp->arg.v);
      tl->toy_main();
    }
    pp->exit = toys.exitval;
    if (toys.optargs != toys.argv+1) free(toys.optargs);
    if (toys.old_umask) umask(toys.old_umask);
    memcpy(&toys, &temp, sizeof(struct toy_context));
  } else {

    // Quick and dirty PATCH
 
    int c;
    for (c=0;pp->arg.v[c] != NULL;c++);
    char *new_argv[c+2];
    new_argv[0] = NULL;
    new_argv[c+1] = NULL;

    char **tocall = pp->arg.v;

    if (tl && TOYBOX_SH_ALWAYS_USE_TOY) {
      new_argv[0] = "./toybox"; // Use argv[0] instead ? or the WhereAmI module ?
      for (int i=0;i<c;i++){
        new_argv[i+1] = pp->arg.v[i];
      }
      tocall = new_argv;
    }

    int pipe[2];

    pipe[0] = 0;
    pipe[1] = 1;
    if (-1 == (pp->pid = xpopen_both(new_argv, pipe)))
      perror_msg("%s: not found", *pp->arg.v);
    else pp->exit = xpclose_both(pp->pid, 0);
  }

  return;
}
```

**Comment by pocomane** [comment]
I give it a try with the last commits and it mostly works. The function is:

```
int toybox_capireplace_system( char * run ){
  static int first_time = 1;
  struct sh_function scratch;
  int prompt = 0;
  
  if (first_time) {
    subshell_imports();
    first_time = 0;
  }

  memset(&scratch, 0, sizeof(scratch));

  run = strdup(run);
  char * dup = run;
  for (;;) {

    // Find next line position
    int i;
    for (i=0; run[i] != '\n' && run[i] != '\0'; i++);
  
    if (i == 0 && run[i]=='\0') break ;
    if (i == 0) {
      run+=1;
      continue;
    }
  
    char o = run[i];
    run[i] = '\0';

    prompt = parse_line(run, &scratch);
//dump_state(&scratch);
    if (prompt != 1) {
// TODO: ./blah.sh one two three: put one two three in scratch.arg
      if (!prompt) run_function(&scratch);
      free_function(&scratch);
      prompt = 0;
    }
    
    run += i;
  }
  free(dup);
}
```

This code does what I was looking for: I can call it from any toy in order to run some script with the internal shell. When it ends the control returns to the caller toy. (Background run is not an issue for the moment).

However when I to call it from a deeply nested function, it starts to fail (i.e. it starts to run external commands instead of the internal toys). I tracked down the issue to toy_exec_which in main.c:166 :

```
  if (!CFG_TOYBOX_NORECURSE && toys.stacktop)
    if (labs((long)toys.stacktop-(long)&which)>6000) return;
```

Increasing the limit from 6000 to 6500 seems to fix this issue too, at least in the my use case[1] : now I can compile lua as a toy and got os.execute call the internal shell toy instead of the OS one. 

- To take into account a more generic use case, is it possible to directly count the number of recursive call to toy_exec_which and always allow, say, the first 3 ?

- Could you add a function similar to toybox_capireplace_system to the mainstream toybox repository?

pocomane

[1] Maybe there will be some problems with lua code that calls c code that calls lua code, but I didn't check.
