### ISSUE TITLE
linker failure for make menuconfig

### ISSUE THREAD

**Issue by cb88** [landley/toybox#13]
kconfig/mconf: $(SHIPPED)
        $(HOSTCC) -o $@ kconfig/mconf.c kconfig/zconf.tab.c \
                kconfig/lxdialog/*.c -lcurses -ltinfo -DCURSES_LOC="<ncurses.h>" \
                -DKBUILD_NO_NLS=1 -DPROJECT_NAME=\"$(KCONFIG_PROJECT)\"

I had to add -ltinfo in kconfig/Makefile otherwise it was missing symbols. This was on Gentoo amd64 just  ask if you need any more specifics! Thanks.

**Comment by landley** [comment]
I believe this was fixed by commit 7cdb8af91477:
http://lists.landley.net/pipermail/toybox-landley.net/2015-August/007610.html
