### ISSUE TITLE
touch timezone field not working

### ISSUE THREAD

**Issue by alexconst** [landley/toybox#130]
The [documentation](https://github.com/landley/toybox/blob/d78f05e91bb3a87a73b1d3fad29362447ee8e1f6/toys/posix/touch.c#L24) states that `-d      set time to DATE (in YYYY-MM-DDThh:mm:SS[.frac][tz] format)`

However running the following command:
`touch -m -d 2019-07-18T16:29:41.951294+0100 foo.txt`
will fail with error message `touch: bad '2019-07-18T16:29:41.951294+0100'`

Existing tests do not make use of the `tz` field, so its use is unclear.

Is this option supported? If so, how can it be used?
Any chance for the documentation to be clarified or a test added?

Thanks

**Comment by enh-google** [comment]
fixed by babcb4bcf4c5c37e545f174db9ba99c62ebb877a and d75a535e000db6eda21275858e4f41fa1591e692.
