### ISSUE TITLE
[feature request] -t flag for cp and install

### ISSUE THREAD

**Issue by E5ten** [landley/toybox#133]
Sets a target directory to put all source arguments in.

**Comment by enh-google** [comment]
3d5cb06e8b5cfcd4226375ff435b1725399fda13 adds -t to install, but not cp/mv.

**Comment by E5ten** [comment]
It would be nice for cp to have it as well, but install was my main priority with this issue, I can close it if there aren't plans to add the flag for cp in the future?

**Comment by E5ten** [comment]
Closed by https://github.com/landley/toybox/commit/6d615c73b321a2f3a337d5d9a949f159d436375b.
