### ISSUE TITLE
stat adds an extra 0 to access bits of files with special permissions enabled

### ISSUE THREAD

**Issue by E5ten** [landley/toybox#134]
If I `stat` a file with set{u,g}id and the sticky bit disabled, the permissions section of the output will correctly display something like `Access: (0755/-rwxr-xr-x)` but if I do the same with a file that has one of the 3 special permissions enabled, in the following example setuid, the expected output would be `Access: (4755/-rwsr-xr-x)` but with toybox stat it is `Access: (04755/-rwsr-xr-x)`.

**Comment by landley** [comment]
Fixed in commit e5942a8c90c2.
