### ISSUE TITLE
find -printf doesn't support \0

### ISSUE THREAD

**Issue by E5ten** [landley/toybox#139]
```
find . -printf '%P\0'
find: bad \0
```
I think this is because when `unescape` is called `0` to `\0` isn't one of the conversions it does (I guess because of C strings being null-terminated?). I managed to make this work with the change below, but I don't know C so it's likely a bad solution.
```--- a/toys/posix/find.c
+++ b/toys/posix/find.c
@@ -568,7 +568,8 @@ static int do_find(struct dirtree *new)
         if (check) for (fmt = ss[1]; *fmt; fmt++) {
           // Print the parts that aren't escapes
           if (*fmt == '\\') {
-            if (!(ch = unescape(*++fmt))) error_exit("bad \\%c", *fmt);
+            if (*++fmt == '0') ch = 0;
+            else if (!(ch = unescape(*fmt))) error_exit("bad \\%c", *fmt);
             putchar(ch);
           } else if (*fmt != '%') putchar(*fmt);
           else if (*++fmt == '%') putchar('%');
```

**Comment by landley** [comment]
In theory \0 is handled as an octal escape, as it is by the echo and printf commands. In practice, this is not the same printf as the code in either of those two places, and doesn't seem to support octal escapes.

**Comment by enh-google** [comment]
(patch with new tests sent to list.)
