### ISSUE TITLE
External 3rd party tools

### ISSUE THREAD

**Issue by technosaurus** [landley/toybox#140]
After looking through #129 and seeing that people are finally using toybox as a building block for multicall binaries that incorporate external projects, I wonder if toybox should address this inevitability.

It seems like devs just need to add/symlink  a directory in ./toys with a README and properly formed app.c file.

Not sure on the best way of adding additional CFLAGS/LDFLAGS for extra dependencies or how to handle license differences (#129 used lua which is MIT for instance)

This could be a great tool for devs, I used it in an experimental build with xfbdev/xvesa, minimal xinit, terminal and jwm to get a ~1mb compressed kernel with a built-in initramfs for qemu.  Obviously those are way outside the scope of the project, but if there was an official way to do things like this, it might stir up interest.

**Comment by enh-google** [comment]
> This could be a great tool for devs

why? unless you're reusing the toybox infrastructure, what's the advantage? (and don't forget that linking in all those extra libraries will slow down toybox startup.)

**Comment by landley** [comment]
"Add one self-contained file and you get a command" is the design idea, yes.

You can set CFLAGS and LDFLAGS in the file "configure" at the top level.

Statically link the libraries and they shouldn't slow startup. (Dynamic linking is expensive, and for a multicall binary has less benefit.)

Toybox is 0BSD, a public domain equivalent license. That means you can add code under any other license you like, and the license of the resulting project is just the license of the other code. (You can stutter your license and retain 0BSD if you like, but are not required to by the 0BSD license terms. From a legal standpoint 0BSD remains the only permission statement allowing you to use the copyrighted upstream toybox code, but that's true whether you get a copy or not, and we don't require third parties to give out copies of information that's on our website. Nothing in the 0BSD license terms should conflict with any other license, it imposes no obligations. We disclaim warantee, but that's _us_ doing that. You're welcome to offer all the implicit or explicit warantees you like. Go nuts.)

**Comment by enh-google** [comment]
nothing obviously actionable here.
