### ISSUE TITLE
[feature request] ln -T flag

### ISSUE THREAD

**Issue by rprichard** [landley/toybox#142]
coreutils ln has a `-T` flag that ensures that the new link name is always treated as a filename rather than a directory name. It's especially useful with `-sf`, because it allows invoking `ln` to create-or-replace a symlink without having to remove the old one first or worry about whether it points to a file or a directory.

e.g.

```
mkdir A B
ln -sf A L # creates a symlink, L -> A
ln -sf B L # creates a link, A/B -> B (broken link)
ln -sfT B L # replaces the link, L -> B
```

It seems like a useful thing to have, but it also doesn't appear widely supported.

Busybox's ln has a `-T` option, but rather than treat the link name as a file, it appears to detect when the link name is a directory and abort. I think that loses most of the benefit of the option.

This came up recently for me when working on a script used with Android (but not one that's likely to use Toybox) -- https://android-review.googlesource.com/c/platform/bionic/+/1127567/1..2.

GitHub Code Search shows some matches for `ln -sfT`: https://github.com/search?p=4&q=ln+-sfT&type=Code

**Comment by jmakip** [comment]
Does this have same effect?

```
ln -sfn B L 
```

**Comment by rprichard** [comment]
I hadn't noticed the `-n` option before. Yeah, that accomplishes most of what I care about, so maybe `-T` isn't needed.

The remaining difference seems to be: `-T` ensures that `ln` fails if a path that was intended to be a new symlink is instead a directory (not a symlink to a directory). busybox's ln has both `-n` and `-T`, and `ln -sfnT B L` with either busybox or coreutils appears to work the same way as `ln -sfT B L` on coreutils.

**Comment by landley** [comment]
I added -T, 51cc908ee406
