### ISSUE TITLE
segfault in ls due to multibyte character

### ISSUE THREAD

**Issue by E5ten** [landley/toybox#146]
When trying to list files in a directory with multibyte characters (one example is specifically `ő`, ls segfaults. This happens because in `crunch_qb`, len is declared unsigned, but then set to wcrtomb's return value, which is -1 when the character `cannot be represented as a multibyte sequence (according to the current locale)` (taken from the wcrtomb manpage). The reason that wcrtomb is returning -1 here, despite the character being representable as a multibyte sequence according to my locale is the `if (CFG_TOYBOX_I18N) setlocale(LC_CTYPE, "C.UTF-8");` in main.c. If len is declared as a signed int instead of unsigned, avoiding the segfault, binary output occurs where the character is. This still happened when I commented the setlocale line just to see what would happen, and of course didn't when I uncommented it but replaced C.UTF-8 with my locale.

**Comment by jmakip** [comment]
I send a patch to mailinglist to fix seqfault when wcrtomb returns -1

With my locale and i18n support on I could not confirm and your char ő prints fine. But if i turn i18n off
I get seqfault. 

link to thread 
http://lists.landley.net/pipermail/toybox-landley.net/2019-October/011026.html
