### ISSUE TITLE
install performs stripping regardless if files were executables or not

### ISSUE THREAD

**Issue by firasuke** [landley/toybox#161]
I don't always encounter this error, but I've noticed it when using the `-D` and `-v` flags. For example, running this command:

```Shell
install -m 644 -Dv file_a file_b file_c file_d target_directory/
```

yields the following errors:
```Shell
strip:./file_a: file format not recognized
strip:./file_b: file format not recognized
strip:./file_c: file format not recognized
strip:./file_d: file format not recognized
```

(Normally I'd add a `-t` before the target_directory/ but I don't think it's possible with toybox's install)

![example](https://imgur.com/B2uXIGE.png)

**Comment by enh-google** [comment]
i'm unable to reproduce this (with glibc at least; i don't have musl, but it's not obvious how musl would affect this).

can you still reproduce this?

**Comment by enh-google** [comment]
can't reproduce.
