### ISSUE TITLE
"chattr =" can't clear attributes

### ISSUE THREAD

**Issue by rprichard** [landley/toybox#172]
By default, when I create a file, it has the "extents" attribute set. If I want to set the attributes to nothing, AFAICT, the syntax is `chattr = <file>`, but toybox isn't accepting that.

gLinux/Ubuntu e2fsprogs:
```
$ touch A
$ lsattr A
--------------e----- A
$ chattr = A
$ lsattr A
-------------------- A
$ chattr +e = A
= is incompatible with - and +
```
Toybox:
```
$ touch A
$ toybox lsattr A
--------------e----- A
$ toybox chattr = A
chattr: need '-p', '-v', '=', '-', or '+'
$ toybox chattr +e = A
```

Toybox appears to handle multiple '=' arguments the same way as e2fsprogs, though, by OR'ing all the flags.

**Comment by enh-google** [comment]
oops. i thought i'd fixed that already, but clearly not. patch sent to list...
