### ISSUE TITLE
How to run Toybox for build automation?

### ISSUE THREAD

**Issue by mcandre** [landley/toybox#175]
Toybox is amazing! I'd like to start using this to compile and test some command line Android applications, emphasizing *automation* for 100% of the steps.

In the past, I would do this for PPC applications using `qemu-ppc-static`, in order to test run PowerPC apps from typical x86 desktop/laptop hosts. Do you know if there is a similar workflow for Android projects?

How could one launch Toybox (mksh) from adb, and redirect an application's stdin/out/err file descriptors to map to the host shell's stdin/out/err file descriptors?

For stdout-only applications, this is somewhat easier using Android loggers. And for networking applications you can just adb port forward. But for CLI applications I am not sure of a way to do this other than the painstaking, manual way.

**Comment by enh-google** [comment]
i don't understand the question. "redirect an application's stdin/out/err file descriptors to map to the host shell's stdin/out/err file descriptors" is what adb _does_. (it also returns the remote process' exit status as its own.)

what specific problem are you having?
