### ISSUE TITLE
Disable UTMPX Automatically

### ISSUE THREAD

**Issue by firasuke** [landley/toybox#185]
Why isn't `CONFIG_TOYBOX_UTMPX` disabled automatically when tools that require utmp/utmpx are disabled?

```Shell
other -> login
other -> uptime
other -> w
pending -> getty
pending -> last
pending -> sulogin
pending -> telnetd
posix -> who
```

Is it ok if I manually disabled `CONFIG_TOYBOX_UTMPX` in the `.config` file?

**Comment by enh-google** [comment]
> Why isn't `CONFIG_TOYBOX_UTMPX` disabled automatically when tools that require utmp/utmpx are disabled?

because `CONFIG_TOYBOX_UTMPX` means "is utmpx _available_?", not "is utmpx _required_?".

> Is it ok if I manually disabled `CONFIG_TOYBOX_UTMPX` in the `.config` file?

yes. Android doesn't have utmpx. we do use uptime(1), but there's code in portability.h to provide no-op implementations of the stuff uptime uses.

**Comment by firasuke** [comment]
Thanks for your answer.

I understand that, but my point is why check for the availability of utmpx if it's not required?

**Comment by enh-google** [comment]
> I understand that, but my point is why check for the availability of utmpx if it's not required?

because that would require building infrastructure to check whether we need to check, which would cost more than just checking anyway and ignoring the result. (the `probesymbol` infrastructure is required for other stuff, so there's no maintenance overhead there.)

**Comment by firasuke** [comment]
That answered my question, thanks!

**Comment by enh-google** [comment]
(if you're curious about some of the other build-time checks that actually pull in libraries, grep for `as-needed` to see how they don't cost you anything unless they're actually needed :-) )
