### ISSUE TITLE
Add HTTPS to lists.landley.net

### ISSUE THREAD

**Issue by Neustradamus** [landley/toybox#228]
Can you add HTTPS to lists.landley.net?

Thanks in advance.

**Comment by enh-google** [comment]
while this would be goo, i think dreamhost hosting issues are out of rob's control (as demonstrated by the archive going down last week).

**Comment by landley** [comment]
I really want https support there too, I have to login with an unencrypted text list password to unblock messages held for moderator approval. Sadly lists.landley.net is an alias into a shared server that's different from the one hosting landley.net. I don't have ssh access to the list server and can barely get Dreamhost to keep it _up_ let alone mirror the let's encrypt info there. Even the top level lists.landley.net index page has been "temporarily disabled" for something like eleven years now, and would probably require https://www.youtube.com/watch?v=5YGc4zOqozo level lobbying to get unstuck at this point.

**Comment by Neustradamus** [comment]
@landley, @enh-google: It is not solved...
Can you reopen it?

**Comment by landley** [comment]
You asked a question, got an answer. "No, I cannot."

I can't fix it. I WANT to fix it, but short of changing hosting providers... I have pestered dreamhost support about this on and off for a decade. If you'd like to ask dreamhost why their lists do not support https, you could always try http://dreamhost.com/contact but if they can't address the issue for paying customers... As I said, it's hard enough getting them to keep the service UP:

https://landley.net/dreamhost.txt
https://landley.net/dreamhost2.txt
https://landley.net/toybox/#12-21-2015

They're cheap, they mean well, the basic "web hosting" part works ok, and it beats me having to try to maintain and secure my own server. But mailing lists are definitely a weak spot for them.
