### ISSUE TITLE
rmdir: New --ignore-fail-on-non-empty behavior

### ISSUE THREAD

**Issue by frikiluser** [landley/toybox#248]
FYI:

New Coreutils has changed ```rmdir --ignore-fail-on-non-empty``` behavior.

See https://github.com/coreutils/coreutils/pull/40

**Comment by landley** [comment]
We never had their bug? https://github.com/landley/toybox/blob/master/toys/posix/rmdir.c#L30 always reports any error other than ENOTEMPTY.
