### ISSUE TITLE
Why is toybox slower than busybox?

### ISSUE THREAD

**Issue by subnut** [landley/toybox#260]
```
❯  /usr/bin/time zsh -c 'for i in $(seq 1 1000); do toybox cal > /dev/null; done'
1.01user 0.71system 0:01.63elapsed 105%CPU (0avgtext+0avgdata 3832maxresident)k
0inputs+0outputs (0major+164905minor)pagefaults 0swaps
❯  /usr/bin/time zsh -c 'for i in $(seq 1 1000); do busybox cal > /dev/null; done'
0.56user 0.38system 0:00.86elapsed 109%CPU (0avgtext+0avgdata 3900maxresident)k
0inputs+0outputs (0major+87435minor)pagefaults 0swaps
❯  /usr/bin/time zsh -c 'for i in $(seq 1 1000); do toybox echo '' > /dev/null; done'
1.03user 0.63system 0:01.58elapsed 105%CPU (0avgtext+0avgdata 3808maxresident)k
0inputs+0outputs (0major+154986minor)pagefaults 0swaps
❯  /usr/bin/time zsh -c 'for i in $(seq 1 1000); do busybox echo '' > /dev/null; done'
0.54user 0.32system 0:00.79elapsed 108%CPU (0avgtext+0avgdata 3900maxresident)k
0inputs+0outputs (0major+82519minor)pagefaults 0swaps
```

On Artix Linux (s6)

**Comment by landley** [comment]
You mean why is the command entry codepath taking 0.0005 seconds longer on your system, which you had to run 1000 times with commands doing nothing to reliably measure?

At a guess, this is a "you" problem. It's reliably the opposite for me here:

$ time busybox echo '' > /dev/null

real	0m0.002s
user	0m0.000s
sys	0m0.000s
$ time busybox echo '' > /dev/null

real	0m0.002s
user	0m0.004s
sys	0m0.000s
$ time toybox echo '' > /dev/null

real	0m0.001s
user	0m0.000s
sys	0m0.000s
$ time toybox echo '' > /dev/null

real	0m0.001s
user	0m0.000s
sys	0m0.000s

Have you checked your filesystem layout to see if busybox is earlier in your $PATH than toybox is?
