### ISSUE TITLE
Nc not sending or receiving all data in some cases

### ISSUE THREAD

**Issue by asm89** [landley/toybox#262]
We found that `nc` is failing to send or receive all data in _some cases_. If data is piped to stdin of the process and the piping process exits fast enough `nc` will exit without reading all data. I can reliably reproduce the behavior.

In one shell start `nc` in listening mode:

```
$ ./toybox nc -L -p 1234
...
```

In a different shell, generate a test file containing 4 kB of `a`s and one `b`.

```
$ python3 -c 'print("a" * 4096 + "b", end="")' > testfile
```

Send the data from the test file to the listening `nc`. Observe that when using `cat` to stdin the final `b` does not show up:

```
$ # this works
$ ./toybox nc localhost 1234 < testfile
$ # this doesn't
$ cat testfile | ./toybox nc localhost 1234
$ # this also works
$ (cat testfile; sleep 1) | ./toybox nc localhost 1234
```

Alternatively let the listening server echo back the number of bytes:

```
$ ./toybox nc -L -p 1234 wc -c
```

Note that the number of bytes does not match when using `cat` without the sleep:

```
$ wc -c testfile
4097 testfile
$ ./toybox nc localhost 1234 < testfile
4097
$ cat testfile | ./toybox nc localhost 1234
4096
$ (cat testfile; sleep 1) | ./toybox nc localhost 1234
4097
```

**Comment by asm89** [comment]
I believe https://github.com/landley/toybox/pull/263 fixes the issue. :)

**Comment by landley** [comment]
I added a continue. Commit 2b4abd05efcc

Thanks for the heads up.
