### ISSUE TITLE
toybox grand scheme for android

### ISSUE THREAD

**Issue by coderofsalvation** [landley/toybox#268]
I'm curious what the thoughts are on the android 29+ way forward:

https://twitter.com/topjohnwu/status/1171308881823195138

and respectively the 'exec()'-part in https://developer.android.com/about/versions/10/behavior-changes-10

> Is the tweet-author forgetting that toybox can actually be accessed over USB (typing `adb shell`) outside of an apk?

**Comment by enh-google** [comment]
yeah, the tweet was talking about Termux which bundled its own utilities. Android also ships toybox as its own command line tools (see https://android.googlesource.com/platform/system/core/+/master/shell_and_utilities/README.md for more detail, by OS version) and AOSP builds (on the host) using toybox https://android.googlesource.com/platform/prebuilts/build-tools/+/master/path/linux-x86/
