### ISSUE TITLE
install -D -t <dir> does not create <dir>

### ISSUE THREAD

**Issue by E5ten** [landley/toybox#270]
This also doesn't work with `install -D file1 file2 dir`, where dir doesn't exist, but busybox also messes that up (differently, instead of making dir and putting file[12] there, it makes dir's parents and makes puts file2 as dir) so I'm not sure what should be done in that situation.
Either way, with any install I've seen that has `-t`, it creates the dir given to `-t` when `-D` is also passed.

**Comment by E5ten** [comment]
Looking at https://github.com/landley/toybox/commit/c42089fed7adbf3ae1a0fd73b3a7b1e4f10e31db, I'm unsure what is preventing install from also being fixed by this commit, but it still seems to have the same issue (while cp -Dt non-existent-dir does work).

**Comment by E5ten** [comment]
Ok I did a bit more experimentation, it seems that `FLAG(D)` in cp_main() is false when running `install -D`, maybe -D also needs a `cp_flag_D()` to translate it?

**Comment by E5ten** [comment]
I'm not sure that this doesn't break anything, but it seems to make install -Dt work:
```diff
--- a/toys/posix/cp.c
+++ b/toys/posix/cp.c
@@ -478,6 +478,7 @@ void mv_main(void)
 static inline int cp_flag_F(void) { return FLAG_F; };
 static inline int cp_flag_p(void) { return FLAG_p; };
 static inline int cp_flag_v(void) { return FLAG_v; };
+static inline int cp_flag_D(void) { return FLAG_D; };

 // Switch to install's flag context
 #define CLEANUP_cp
@@ -528,7 +529,7 @@ void install_main(void)

   // Translate flags from install to cp
   toys.optflags = cp_flag_F() + cp_flag_v()*!!FLAG(v)
-    + cp_flag_p()*!!(FLAG(p)|FLAG(o)|FLAG(g));
+    + cp_flag_p()*!!(FLAG(p)|FLAG(o)|FLAG(g)) + cp_flag_D() * !!FLAG(D);

   TT.callback = install_node;
   cp_main();
```

**Comment by E5ten** [comment]
https://github.com/landley/toybox/commit/e6207d5e0f42452e96c66a9173b3d17468629beb has a test failure, I think the issue is the `FLAG(D)` at line 376. I'm not sure what the rules on how cp's -D should work are, if it's different from install (and so that condition is correct for it) then I think the `FLAG(D)` needs to be changed to `(FLAG(D) && *toys.which->name != 'i')` maybe?

**Comment by landley** [comment]
In a clean checkout, make test_cp and make test_mv both pass. Since you didn't give any other information about the test failure (WHICH test are you saying failed? What was the output?) I'm closing this as "works for me".

**Comment by E5ten** [comment]
I was basing this on the github automated testing result. The test failure is for install, not cp or mv. For an example to illustrate the same failure as in the automated test:
`./toybox install -D Config.in a/b`
this should create directory "a" and copy Config.in to "a/b", instead it outputs `install: a/b/Config.in not under a/b`
The reason this is happening is that the new translation of install -D to cp -D when install calls cp_main() breaks things, because -D/--parents in cp has a different effect from the one that install -D should have. The only reasonable solution I can see to this is to remove the -D translation, and handle install -D -t in install_main(). Otherwise I think pretty much every FLAG(D) condition in cp_main() would have to be accompanied by a corresponding check that the command being run is actually cp or mv, and not install calling cp_main().

**Comment by E5ten** [comment]
Like to be clear, this isn't just an install -t problem now, the translation of -D from install to cp has lead to install flags/invocations that previously worked being broken (hence the failing automated test)

**Comment by enh-google** [comment]
yeah, in a clean checkout `make tests` fails:
```
install: 'a/b' not directory
FAIL: install install -D exists
echo -ne '' | mkdir -p a; touch a/b; install -D random a/b && cmp random a/b && echo yes
--- expected	2021-02-22 09:17:20.226369019 -0800
+++ actual	2021-02-22 09:17:20.230368973 -0800
@@ -1 +0,0 @@
-yes
make: *** [Makefile:76: tests] Error 1
```

**Comment by E5ten** [comment]
I think that since -D can't be passed on to cp_main(), the solution here is to handle the -D -t case within install_main()

**Comment by lulcat** [comment]
This has been a bit of a rewrite for me in a ton of packages locally :p glad to see someone finding time to do some patchwork :)

**Comment by E5ten** [comment]
Currently I'm also seeing this:
`./toybox install -D file1 file2 dir`
gives `install: 'dir' not directory`
but it works if I do the same invocation but instead of `dir` I use `dir/` (note trailing slash)
I'm not clear on why this doesn't work, or why it does with a trailing slash (shouldn't be required when there's more than one source file), but it seems relevant to this.

**Comment by E5ten** [comment]
ping?

**Comment by landley** [comment]
I reverted the broken commit.

**Comment by E5ten** [comment]
I meant about the initial issue, because the broken commit was an attempt to fix it, not the original problem

**Comment by E5ten** [comment]
Closed by https://github.com/landley/toybox/commit/3cde24138ac06e384965db2944e858d2110ecacb
