### ISSUE TITLE
xsignal and SA_RESTART

### ISSUE THREAD

**Issue by E5ten** [landley/toybox#271]
Typically, the SA_RESTART flag is desired behaviour for establishing signal handlers (and this is what the signal functions in glibc and musl do). I'm not sure if there's a specific reason this isn't being used, but if not, it might be worth considering changing xsignal to call xsignal_flags with SA_RESTART instead of 0 as the flags argument.

**Comment by landley** [comment]
It leads to a lot of situations where "I hit ctrl-c but can't break out of the read() because it endlessly restarts". Your signal handler has to siglongjmp() rather than being able to check toys.signal in the processing loop.
