### ISSUE TITLE
cp -u

### ISSUE THREAD

**Issue by aheirman** [landley/toybox#277]
The 
```
-u, --update
    copy only when the SOURCE file is newer than the destination file or when the destination file is missing
```
flag is missing.

I know it's not in https://pubs.opengroup.org/onlinepubs/9699919799/utilities/cp.html but it is in https://linux.die.net/man/1/cp

Anyhow, love the project.

**Comment by aheirman** [comment]
It is in busybox, https://git.busybox.net/busybox/tree/coreutils/cp.c

**Comment by landley** [comment]
I'm assuming "newer" means mtime, not ctime?

Honestly, why do linux filesystems bother to _store_ nanoseconds if the OS uses jiffies?

```
$ echo two > two; echo one > one; ./cp -u one two; cat two
old=1617796468.730506587 new=1617796468.730506587
one
```

Added a sleep .1 to the test. Commit 2a6f03eb088b
