### ISSUE TITLE
sort: fails to strip list

### ISSUE THREAD

**Issue by sdsddsd1** [landley/toybox#290]
Hey,
I have a given directory structure where I need to strip everything but one toplevel. The `sort` from toybox somehow fails this operation. Tested also with busybox, sbase and coreutils which all show the right result.
```
/tmp $ tree testing/                                                               
testing/
├── 1
│   ├── test1
│   └── test2
├── 2
│   ├── test3
│   └── test4
├── 3
│   ├── test5
│   └── test6
└── 4

10 directories, 0 files
```
  
  

'sort' from busybox does the right result. Strip every toplevel but one. 
```
/tmp $ find testing | /home/claudia/bin/busybox sort -ut / -k1,1 
testing
```
  
  

'sort' from toybox does not filter the toplevel directories.
```
/tmp $ find testing | /usr/bin/toybox  sort -ut / -k1,1                            
testing
testing/1
testing/1/test1
testing/1/test2
testing/2
testing/2/test3
testing/2/test4
testing/3
testing/3/test5
testing/3/test6
testing/4
```

**Comment by gregschmit** [comment]
Is the issue that `-u` should be using the first field (defined because `-t /` is specified) as the unique index? Perhaps right now `-u` is always using the whole line as the unique index and we just need it to respect that `-k1,1` indicates to use the first field as the uniqueness index?

**Comment by landley** [comment]
The issue was that (according to posix) -u should enable -s. Try now?
