### ISSUE TITLE
tar issue on unlink for POSIX systems

### ISSUE THREAD

**Issue by dlegaultbbry** [landley/toybox#294]
This line can be wrong for POSIX compliant systems leading to test failures

https://github.com/landley/toybox/blob/master/toys/posix/tar.c#L533

The return value is EPERM for these systems.

```
EPERM  The system does not allow unlinking of directories, or
              unlinking of directories requires privileges that the
              calling process doesn't have.  (This is the POSIX
              prescribed error return; as noted above, Linux returns
              EISDIR for this case.)
```

So perhaps EISDIR || EPERM might be better suited.

**Comment by enh-google** [comment]
fixed by a3b423c58e6f67131ef5f1874fc6bd38880322b6
