### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by itsmohitmkk** [landley/toybox#303]
Readme.MD looks like normal text. Style it and make it more readable to users, with hyperlinks and a dynamic colour pallet.

**Comment by michael105** [comment]
And some blinking text. ^^
Sry

**Comment by owl4ce** [comment]
😄

**Comment by itsmohitmkk** [comment]
Yeah sure 😂.  Did what i could : https://github.com/itsmohitmkk/toybox/tree/Updated-Readme

**Comment by enh-google** [comment]
rob doesn't seem keen on markdown...
