### ISSUE TITLE
mkroot.sh always fails when BUILTIN=1 is set

### ISSUE THREAD

**Issue by iggyvolz** [landley/toybox#305]
Found this working on tianon/dockerfiles#133: https://github.com/landley/toybox/blob/4824756b7a0ac7714d35ccbc6467b4afe6b9bab8/scripts/mkroot.sh#L272-L275 will always exit 1 if BUILTIN=1 is set; rather than only exiting 1 on failure.  In 0.8.5: https://github.com/landley/toybox/blob/7a48df38d47057c74d31ac6f80e3aa2b0e88f9af/scripts/mkroot.sh#L247-L250, the line was skipped if BUILTIN=1 rather than exiting.

My bash skills aren't the greatest but I believe the issue could be fixed by surrounding `announce` to `exit 1` in `{ }`?

**Comment by landley** [comment]
Ooops, sorry. Commit ea4748a7cbfa
