### ISSUE TITLE
cp --preserve=xattr also copies selinux context

### ISSUE THREAD

**Issue by dariofreni** [landley/toybox#307]
```
vsoc_x86_64:/ # mkdir -p /data/misc_ce/0/apexdata/apex.apexd_test
vsoc_x86_64:/ # mkdir -p /data/misc_ce/0/apexrollback/123456/apexd.apexd_test
vsoc_x86_64:/ # echo foo > /data/misc_ce/0/apexdata/apex.apexd_test/foo.txt
vsoc_x86_64:/ # ls -aldZ /data/misc_ce/0/apexdata/apex.apexd_test/foo.txt

-rw-rw-rw- 1 root root u:object_r:apex_module_data_file:s0  4 2021-12-21 15:19 /data/misc_ce/0/apexdata/apex.apexd_test/foo.txt

vsoc_x86_64:/ # cp /data/misc_ce/0/apexdata/apex.apexd_test/foo.txt /data/misc_ce/0/apexrollback/123456/apexd.apexd_test
vsoc_x86_64:/ # ls -aldZ /data/misc_ce/0/apexrollback/123456/apexd.apexd_test/foo.txt

-rw-rw-rw- 1 root root u:object_r:apex_rollback_data_file:s0  4 2021-12-21 15:24 /data/misc_ce/0/apexrollback/123456/apexd.apexd_test/foo.txt

vsoc_x86_64:/ # rm /data/misc_ce/0/apexrollback/123456/apexd.apexd_test/foo.txt
vsoc_x86_64:/ # cp --preserve=mode,ownership,timestamps,xattr /data/misc_ce/0/apexdata/apex.apexd_test/foo.txt /data/misc_ce/0/apexrollback/123456/apexd.apexd_test
vsoc_x86_64:/ # ls -aldZ /data/misc_ce/0/apexdata/apex.apexd_test/foo.txt

-rw-rw-rw- 1 root root u:object_r:apex_module_data_file:s0  4 2021-12-21 15:19 /data/misc_ce/0/apexrollback/123456/apexd.apexd_test/foo.txt
```

This is because selinux context is carried in the `security.selinux` xattr. However, I believe that attribute should be excluded unless `--preserve=context` is set. It seems that coreutils cp behaviour is consistent with my understanding.

(This is problematic because it effectively forces us to grant `relabelto` / `relabelfrom` permission if we want to use the flag)

/cc @martijncoenen @enh @enh-google

**Comment by landley** [comment]
Awaiting Elliott's opinion. (Not my area.)

**Comment by dariofreni** [comment]
Elliot is out for almost 3 weeks as far as I can se. I have tested this thoroughly as part of working on https://android-review.googlesource.com/c/platform/system/apex/+/1929445 . Any chance you could take a look or we could find someone else to take a look?

**Comment by landley** [comment]
I believe that you tested your use case, but this is a significant API change I don't understand.

The previous logic was if (!xattr && !security) continue; Your new logic is if (!context && security) continue; That looks like --xattr would ONLY copy security before, and --context would copy everything. Now --context copies everything and --xattr copies everything EXCEPT security? Is that correct?

I would expect if security's being treated specially that one option would copy only security and the other would copy everything else, but I haven't used extended attributes since OS/2 and have no idea what gnu cp thinks it's doing. The cp man page includes the string "xattr" exactly once, in the list of options --preserve can take, and doesn't actually say what it DOES. I broke down and checked busybox, but their cp.c and libbb/*.c do not include the string "xattr".

**Comment by landley** [comment]
I can't get test cases from the bugs you linked to because google's "issuetracker" site is a login screen, even to just read the bug.

**Comment by dariofreni** [comment]
The test cases are in the CL linked, specifically here: https://android-review.googlesource.com/c/platform/system/apex/+/1929445/1/apexd/apexservice_test.cpp . The issuetracker contains references to problems with not copying the xattr, but that's not relevant to toybox.

I believe that the desired logic should be:
1. --xattr copies everything EXCEPT security -- I'm positive that this is what coreutils `cp` does, and furthermore the current behaviour of copying everything would require the selinux policy in the system to grant the process both setxattr and "relabelfrom" "relabelto".
2. --context copies only security.  You are right that my patch makes it copy everything, but that's not a regression compared to the current code.

My patch addresses 1. only.

I believe that in order to address 2. a different approach should be taken. I browsed around and the right way to address 2. doesn't seem to be by means of `setxattr`, but instead it should use `setfscreatecon(3)` before creating the file (see [this](https://yakking.branchable.com/posts/moving-files-7-difficult-xattrs/) link, paragraph "If the file context should be preserved from the original file").

**Comment by landley** [comment]
The logic wasn't designed with setfscreatecon() in mind (sequencing's wrong) and it's a larger redesign to retcon it in there than I'm comfortable with without a _lot_ more test cases. (I'd need a system with selinux set up in a way that barfs on the label-after-create but allows the fscreatecon(). I have todo items to make proper test setups out of mkroot but haven't opened that can of worms yet).

Also, you can have both. --preserve=xattr,context so it isn't _two_ cases, it's four.

I applied your commit and then made a stab at it (e1917654af98), which compiles and passes make test_cp. Tell me what you think? (Note, if Elliott isn't back for 3 weeks, he presumably won't be pulling the repo into the AOSP build...)

**Comment by dariofreni** [comment]
Thanks! I've prepared a merge of your latest changes here: https://android-review.googlesource.com/c/platform/external/toybox/+/1931083 . I'll wait for Elliott to be back to review it unless this becomes urgent (it shouldn't).

I tested your change and it addresses my use cases correctly. Thanks a lot for your prompt response!
