### ISSUE TITLE
sort -h: doesn't respect SI suffix rule

### ISSUE THREAD

**Issue by kasperk81** [landley/toybox#312]
manpage:

> -h, --human-numeric-sort, --sort=human-numeric
> &nbsp;&nbsp;&nbsp;Sort by numerical value, but take into account the SI suffix, if present.	Sort first by numeric sign (negative, zero, or positive);
> &nbsp;&nbsp;&nbsp;then by SI suffix (either empty, or `k' or `K', or one of `MGTPEZY', in that order); and finally by numeric value.  The SI suffix
> &nbsp;&nbsp;&nbsp;must immediately follow the number.  **<ins>For example, '12345K' sorts before '1M', because M is "larger" than K.</ins>**  This sort option is use-
> &nbsp;&nbsp;&nbsp;ful for sorting the output of a single invocation of 'df' command with -h or -H options (human-readable).

```sh
$ cat << EOF | sort -h
450K    ./x2
1.2M    ./x4
202K    ./x1
2.6M    .
0.3M    ./x3
EOF
```

on debian gives expected/documented result:
```sh
202K    ./x1
450K    ./x2
0.3M    ./x3
1.2M    ./x4
2.6M    .
```
toybox result:
```sh
202K    ./x1
0.3M    ./x3
450K    ./x2
1.2M    ./x4
2.6M    .
```

**Comment by landley** [comment]
$ echo -e '12345K\n1M' | sort -h
12345K
1M

Huh, you're right, the gnu "sort -h" feature is fundamentally broken. I'll remove it.

**Comment by landley** [comment]
Commit b0a4a96e36da
