### ISSUE TITLE
Expand on ambiguous characters in pwgen

### ISSUE THREAD

**Issue by terefang** [landley/toybox#313]
i would like to propose the following additional ambiguous characters:

* ´8´ vs ´B´
* ´5´ vs ´S´
* ´2´ vs ´Z´

some might consider also:

* ´D´ vs ´0´ vs ´O´

**Comment by landley** [comment]
Let's see...

$ pwgen -B 10 100000 | grep '[8B5S2ZD0O]'

Zero hits. Commit 25fd949e513b

**Comment by terefang** [comment]
wow ... the most responsive type of guy !

thank you very much

is this going into the 0.8.7 release ?
