### ISSUE TITLE
Regression: find stops supporting -newerXY

### ISSUE THREAD

**Issue by victorhsieh** [landley/toybox#318]
`find` used to support `-newerXY`, for example `find -newerct '@1644267868'`, but the support was dropped in https://github.com/landley/toybox/commit/4824756b7a0ac7714d35ccbc6467b4afe6b9bab8#diff-02efacbb8d9317ea910e320f93db4ceed1a43cd443f80aaa99610ef60e79e4d5L463.  It was perhaps not intentional since the option is still in --help.

I tried to simply replace `!strcmp(s, "newer")` with the original `strstart(&s, "newer")`, but it failed with `find: bad group '@1644267868'`.  It'd be nice if someone familiar with the code can fix this bug.

**Comment by landley** [comment]
Commit cfa8d336db1b

**Comment by victorhsieh** [comment]
Thanks for the quick fix. I confirmed the fix is working.
