### ISSUE TITLE
toybox add permissions for android 

### ISSUE THREAD

**Issue by ExtinctDrift19** [landley/toybox#324]

**Comment by landley** [comment]
Could you please be a little more specific?

**Comment by ExtinctDrift19** [comment]
toybox permissions for android similar to busybox for android

**Comment by enh-google** [comment]
it might be easier if you explain your problem in your own language, and we use Google Translate?

do you want toybox in termux, like busybox is? if so, you need to file an issue with termux here: https://github.com/termux/termux-packages/issues
