### ISSUE TITLE
tar hanging on directories starting with two dots

### ISSUE THREAD

**Issue by hg42** [landley/toybox#327]
coming from an issue in OAndBackupX (note the X, now renamed to Neo Backup) I found that toybox tar cannot pack directories that start with two dots.

I am using this shell script in the toybox source directory:

```
#!/bin/zsh

make clean
make defconfig
make tar
make test_tar

dir=/tmp/test_tar

mkdir -p $dir/..dotsdir
touch    $dir/..dotsdir/file

#./toybox tar -c $dir | ./toybox tar -t
./tar -c $dir | ./tar -t
```

I tracked this down to commit 7617d9cf (unfortunately it's a bigger changeset), commit 1387c0a6 works.

You can also add a test (I didn't determine the sum yet, thus I set this to zeros):
```
mkdir dir
testing "create dir" "$TAR dir | SUM 3" \
  "05739c423d7d4a7f12b3dbb7c94149acb2bb4f8d\n" "" ""

testing "pass dir" "$TAR dir | LST" \
  "drwxrwxr-x root/root 0 2009-02-13 23:31 dir/\n" "" ""



#### testing dotsdir
mkdir ..dotsdir
testing "create ..dotsdir" "$TAR ..dotsdir | SUM 3" \
  "0000000000000000000000000000000000000000\n" "" ""

testing "pass ..dotsdir" "$TAR ..dotsdir | LST" \
  "drwxrwxr-x root/root 0 2009-02-13 23:31 ..dotsdir/\n" "" ""
#### end dotsdir



# note: does _not_ include dir entry in archive, just file
touch dir/file
testing "create file in dir" "$TAR dir/file | SUM 3" \
  "2d7b96c7025987215f5a41f10eaa84311160afdb\n" "" ""
```

If it's not a quick fix for you, I could also debug this (however, I first need to setup a C development environment or debugger)

**Comment by hg42** [comment]
more tests to be placed in the script (only enable one of them):

```
if false; then
  # works
  mkdir -p $dir/dots..dir
  touch    $dir/dots..dir/file
fi

if false; then
  # fails
  mkdir -p $dir/..dotsdir
  touch    $dir/..dotsdir/file
fi

if false; then
  # fails
  mkdir -p $dir/...dotsdir
  touch    $dir/...dotsdir/file
fi

if false; then
  # fails
  mkdir -p $dir/dir
  touch    $dir/dir/..dotsfile
fi
```

**Comment by landley** [comment]
Thanks. Commit 4fca350fb34c

**Comment by hg42** [comment]
I tracked it down to tar.c line 224, which is an endless loop in this case:

```
  for (lnk = hname;;) {
    if (!(lnk = strstr(lnk, ".."))) break;
    if (lnk == hname || lnk[-1] == '/') {
      if (!lnk[2]) goto done;
      if (lnk[2]=='/') lnk = hname = lnk+3;
    } else lnk+= 2;
  }
```
I'm not sure what's the exact purpose of these lines, but I am quite sure, the `else lnk+= 2;` needs also be executed in case the dots are neither followed by zero nor by "/".

**Comment by hg42** [comment]
LOL, you are fast :-)

**Comment by hg42** [comment]
ok, works so far...
thanks for the fix
