### ISSUE TITLE
tar: does not support "strip-components" option

### ISSUE THREAD

**Issue by CameronNemo** [landley/toybox#330]
Does not support the option, which appears to be used by some NixOS tool.

>--strip-components=NUMBER
>strip NUMBER leading components from file names on extraction

**Comment by landley** [comment]
I'm a little unclear on what this does. Specifically, which things it affects. It doesn't affect the -t output strings. It seems like directories with all their segments consumed are skipped, does that mean they don't wind up changing timestamp/ownership/permissions of the current directory? Are collisions "newest one stomps" or "oldest is kept" or what? Sigh: it would be nice if there was an actual specification for the non-obvious bits...

**Comment by landley** [comment]
My first guess is commit 72e7e3821b4a

**Comment by landley** [comment]
In the absence of a reply, I'm assuming that commit did what you needed.

**Comment by CameronNemo** [comment]
sorry I meant to test but have not been able to. I will let you know if I run into problems with this.
