### ISSUE TITLE
Can toybox support chinese?

### ISSUE THREAD

**Issue by mtkfleet** [landley/toybox#335]
Dear sirs,

I use "ls" in toybox, but the chinese file can not show. 
will you plan to support chinese?

Thanks a lot!

**Comment by enh-google** [comment]
toybox _does_ support chinese --- developers use that on Android all the time.

what OS are you running toybox on? what locale? what are your LC_* environment variables set to? what encoding are you using for your filenames (UTF8? GBK?) and does your locale correspond?

if you're running toybox on another device (Android, say) but looking at the results on another computer --- what are the answers to all the above questions, but for your computer instead?

the output of `ls | xxd` might be interesting too (if you also paste in the correct filenames) so we can see what _is_ being sent.

**Comment by landley** [comment]
Toybox is designed for utf-8 encoding. I don't have specific chinese tests, but https://github.com/landley/toybox/tree/master/tests/files/utf8 has various snippets that get run through the commands during "make tests" to ensure it can count characters not bytes, parse character boundaries, handle combining characters, and so on.

**Comment by mtkfleet** [comment]
> Toybox is designed for utf-8 encoding. I don't have specific chinese tests, but https://github.com/landley/toybox/tree/master/tests/files/utf8 has various snippets that get run through the commands during "make tests" to ensure it can count characters not bytes, parse character boundaries, handle combining characters, and so on.


thank you for your reply, it seams that:
1. if there are UTF-8 content in the file. I use "cat xxx.txt", it can show OK. 
2. but if I rename the file/folder name with the same UTF-8 charaters, I use "ls", it show "???"

For detail:
the file is in the USB, I plug the USB in a linux device with both busybox tool and toybox tool. 
mount -o iocharset=utf8,umask=007 /dev/sda1 /mnt

I use busybox "ls", it shows:
System Volume Information  新建文件夹 新建 文本文档.txt

In the same folder, I use toybox "ls | xxd", it shows:
00000000: 5379 7374 656d 2056 6f6c 756d 6520 496e  System Volume In
00000010: 666f 726d 6174 696f 6e0a 1a1a 201a 1a1a  formation... ...
00000020: 1a2e 7478 740a 0c0c 0c0c 0c0a            ..txt.......

the "1a1a201a...", is not correct UTF-8 code, and when I use busybox "ls | xxd", the UTF-8 code is correct. 

but if I put the UTF-8 characters into a file.txt, and cat it, it shows correct. 

Is there are bug in "ls" for UTF-8?

**Comment by landley** [comment]
It works fine for me here. Do you have a shell alias adding flags? What filesystem are you using? If you use shell wildcard expansion (echo dir/*) what do you see?

**Comment by mtkfleet** [comment]
My toybox version:
$ ./toybox --version
toybox 0.8.6-146-gf29ec45e39ec

I was used default toybox version in my ARM SOC device, no alias setting. 
The file system is FAT32.

It seams "echo" is fine, but "ls" is NG. as following:

$ ./toybox ls 
toybox  \200\\\ \\\\\\\\.txt  \200\\\\\\\\

$ ./toybox echo *
toybox 新建 文本文档.txt 新建文件夹

**Comment by enh-google** [comment]
what libc are you using?

**Comment by landley** [comment]
On 4/27/22 03:37, mtkfleet wrote:
> My toybox version:
> $ ./toybox --version
> toybox 0.8.6-146-gf29ec45e39ec
> 
> I was used default toybox version in my ARM SOC device, no alias setting.
> The file system is FAT32.
> 
> It seams "echo" is fine, but "ls" is NG. as following:
> 
> $ ./toybox ls
> toybox \200\\ \\\\.txt \200\\\\

Octal 200 is binary 128, which is only valid as an additional byte, not as a
first byte.

https://en.wikipedia.org/wiki/UTF-8#Encoding

And the rest of the characters are backslash pairs, which is an escaped
backslash. So what toybox is reporting is "I did not see utf8 encoded unicode
bytes".

Could you try the relevant binary version from
https://landley.net/toybox/downloads/binaries/latest/ and see if that can ls
properly on your system? They're statically linked against musl-libc so should
run on android or a linux distro just fine if you grab the right architecture.

> $ ./toybox echo *
> toybox 新建 文本文档.txt 新建文件夹

$ touch 新建 文本文档.txt 新建文件夹
$ toybox ls
文本文档.txt  新建  新建文件夹

It's working fine for me here...

Rob

**Comment by mtkfleet** [comment]
Hi Rob,

I downloaded the toybox-armv7l from https://landley.net/toybox/downloads/binaries/latest/, and put it into my device.
It works fine for me:
```bash
 ./toybox-armv7l ls
toybox-armv7l  新建\ 文本文档.txt  新建文件夹
```

I saw the toybox-armv7l is statically linked against musl-libc, but my toybox is dynamically linked against glibc-2.31, so it's the glibc issue?

landley.net

Index of /toybox/downloads/binaries/latest
Index of /toybox/downloads/binaries/latest Name Last modified Size Description Parent Directory - toybox-aarch64 2021-12-01 20:52 774K toybox-armv4l 2021-12-01 20:52 753K toybox-armv5l 2021-12-01 20:5

**Comment by landley** [comment]
I'm building against glibc-2.28 here and it works fine for me?

**Comment by qianqiangliu** [comment]
Hi Rob,

After generating locales for glibc, the 'ls' command works fine now.
