### ISSUE TITLE
`xxd -r` fails to read input file

### ISSUE THREAD

**Issue by richmilne** [landley/toybox#338]
I was curious to see whether a [problem with BusyBox's xxd implementation](https://bugs.busybox.net/show_bug.cgi?id=14786) exists in Toybox - but I wasn't able to even read the sample file which illustrates the error.

Here's how to create the sample file:

    $ cat > sample << EOF
    00000000: 0100 0000 0000 0000 0000 0000 0000 00ff  deadbeef........
    EOF

And here's what I tried to do:

    $ /bin/toybox xxd -r sample | xxd
    xxd: sample: seek failed: Invalid seek

BusyBox's xxd and the stand-alone xxd at least produce some non-error output for that command.

The commands were run in Alpine Linux 3.15.4, and version `Toybox 0.8.6 multicall binary`. Under that release of Alpine Linux, the `toybox` binary wasn't available from the main repository, and had to be installed from the testing repo (`apk add toybox --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/`) - so it may be the problem is due to how the binary was built and packaged for this distro.

**Comment by enh-google** [comment]
yeah, this reproduces on ToT too. patch sent to the mailing list...
