### ISSUE TITLE
Inconsistent generated/help.h -- HELP_mke2fs_journal junk chars

### ISSUE THREAD

**Issue by frikiluser** [landley/toybox#367]
Hi,

I've found "random":qa chars in generated/help.h file:
`419: #define HELP_mke2fs_journal "usage: í^\V [-E stride=###] ...`

Steps to reproduce:
```
make allyesconfig
make
cp generated/help.h help.h-saved
make clean
make allyesconfig
make
cp generated/help.h help.h-saved2
diff help.h-saved help.h-saved2
```

It fails to build under some conditions. See this build log: https://salsa.debian.org/debian/toybox/-/jobs/3121739

Best regards,

**Comment by frikiluser** [comment]
It seems to be related to `CONFIG_MKE2FS_JOURNAL`, `CONFIG_MKE2FS_LABEL` and `CONFIG_MKE2FS_EXTENDED`...

When 2 or more options are enabled the junk appears in `generated/help.h`.

Hope it helps 😵‍💫

**Comment by landley** [comment]
In toys/pending, yes.

Here's where the README talks about pending:
https://github.com/landley/toybox/blob/master/README#L81

Here's where "make help" talks about defconfig vs allyesconfig and why you probably want the first:
https://github.com/landley/toybox/blob/master/kconfig/Makefile#L51

Here's where the build emits a warning (in red) if you've enabled stuff out of pending:
https://github.com/landley/toybox/blob/master/scripts/make.sh#L70

Here's the readme in the toys/pending directory:
https://github.com/landley/toybox/blob/master/toys/pending/README#L1

Here's where the FAQ mentions pending:
https://landley.net/toybox/faq.html#:~:text=pending

**Comment by landley** [comment]
P.S. there's an entire page basicallly devoted to it: https://landley.net/toybox/cleanup.html

Which is https://github.com/landley/toybox/blob/master/www/cleanup.html in the repository.

**Comment by landley** [comment]
To clarify the close status: finishing mke2fs needs to fix the help, but playing with help text of unifinshed commands in pending... the command doesn't _do_ anything yet.
