### ISSUE TITLE
Running toybox-aarch64 tar standalone in adb shell "Function not implemented"?

### ISSUE THREAD

**Issue by mmortal03** [landley/toybox#370]
I have been having an unrelated issue with the toybox 0.7.4 tar that is included in my phone's TWRP recovery (twrp-3.6.2_9-0-hima.img) -- no need to go into details on this -- but, to troubleshoot, I thought I'd see if I could just run the latest toybox tar in a standalone manner, to compare the result. However, this resulted in its own issue.

This is what I tried:

>chmod 0777 toybox-aarch64
>./toybox-aarch64 tar -tvf test.tar test.txt
`-rwxrwxrwx root/root       535  2022-08-21 03:30 test.txt`

So, viewing the contents works. However:

>./toybox-aarch64 tar -xvf test.tar test.txt
`test.txt`
`tar: Function not implemented`
`tar: had errors`

The extracted test.txt file is blank (it should be 535 bytes).

Any idea what the issue is?

**Comment by landley** [comment]
Hmmm... Ah, it's returning ENOSYS instead of EINVAL.

Commit 63f787b602f7 and I put a temporary binary at https://landley.net/toybox-aarch64 if you want to test it?

**Comment by mmortal03** [comment]
Thanks! That works!
