### ISSUE TITLE
toybox probing truncates build log

### ISSUE THREAD

**Issue by dlegaultbbry** [landley/toybox#375]
We're building toybox as part of larger set of projects and basically the global make command we launch is akin to

make ... > log.txt 2>&1

But for some reason when toybox executes its build, it basically truncates the build log only leaving the last compiled libprobe line + everything that comes after.

I've traced back the issue to this line: https://github.com/landley/toybox/blob/master/scripts/make.sh#L88

The &>$X is the problem, removing it avoids the issue entirely for us.

We always build with V=1 so perhaps this was never seen before it was changed in 0.8.7.

Not asking you to change anything, just reporting it in case someone stumbles on the same issue if they build toybox in a similar way that we do. I can't really explain how it happens and why without investing more time. I've just deleted that part in our port and the build proceeds as it did before without issue.

**Comment by dlegaultbbry** [comment]
Someone on our build team reproduced the issue locally in case there is any interest

> some_script.sh
> 
> #!/bin/bash
> 
> echo "1"
> echo "2"
> echo "3" &>/dev/stderr
> echo "4"
> echo "5"
> 
> some_wrapper.sh
> 
> #!/bin/bash
> echo "running some_script.sh, see: test_log.txt"
> ./some_script.sh > test_log.txt 2>&1
> echo "DONE"
> 
> Running
> 
> $ ./some_wrapper.sh
> running some_script.sh, see: test_log.txt
> DONE
> 
> output
> 
> $ cat test_log.txt
> 3
> 4
> 5
>

**Comment by landley** [comment]
In your "locally reproduced" example, the 3 that you redirected to /dev/stderr is in test_log.txt, and was not output to the wrapper's stdout?

I did "make distclean defconfig toybox V=1 >filename 2>&1" on devuan beopigs and wrote everything to the file just fine for me too.

The /dev/stderr link should be an alias for filehandle 2 in the current process context (I.E. /proc/self/fd/2) and if you write to that it should go wherever filehandle 2 has been redirected to...? Which in this case 2>&1 says wherever filehandle 1 pointed at the time of redirection (does a dup2() under the covers).

If it's not working for you... what shell are you using on that build system? (Should be bash: scripts/make.sh says #!/bin/bash at the top and the way Makefile is invoking it should let it call its own shell...?)

**Comment by dlegaultbbry** [comment]
Basically, when 3 is echo'd, all the lines before in the file vanish as if the file had just been re-opened with O_TRUNC. This only fails when you have this complex setup of scripts. When I build toybox alone with a log redirect I don't get this problem as you tried.

This is ubuntu with bash.

**Comment by landley** [comment]
Try commit 92252a200375

**Comment by landley** [comment]
Try commit 10325745e3a3

**Comment by dlegaultbbry** [comment]
Last change works for me on Ubuntu.
