### ISSUE TITLE
scripts/single.sh should use gsed when running on macOS

### ISSUE THREAD

**Issue by wbpayne22902** [landley/toybox#378]
Currently when trying to build a single app on macOS with toybox 0.8.8-51-ga7e49c3c7860 `scripts/single.sh` errors out because it's calling `sed` instead of `gsed`.  I've already installed GNU sed from Homebrew and all that is required is to change all instances of `sed` to `gsed` in the script to allow the build to complete successfully.

I know that probably scripts/single.sh should do a check to see if it is running on macOS and then see if `gsed` is available and use it instead of the `sed` included in the base OS install.  If it cannot find an installed version of `gsed` it should return an error instructing the user to obtain `gsed`.  I do not know much about shell scripting or I would submit a pull request with a fix.

**Comment by landley** [comment]
Try commit 8ed0bfe6e3b9

**Comment by wbpayne22902** [comment]
I can confirm that commit 8ed0bfe has fixed this bug.  Everything works as expected on macOS now.
