### ISSUE TITLE
pmap subcommand has two -q flags in help

### ISSUE THREAD

**Issue by lnee94** [landley/toybox#380]
Toybox 0.8.8 multicall binary (see toybox --help)

usage: pmap [-pqx] PID...

Report the memory map of a process or processes.

-q      Show full paths
-q      Do not show header or footer
-x      Show the extended format

the -q for Show full paths
and the -q for Do not show header or footer are the same

**Comment by landley** [comment]
Thanks. Commit a09e7d899b9d
