### ISSUE TITLE
comm: No file -: No such file or directory

### ISSUE THREAD

**Issue by mtboehlke** [landley/toybox#381]
Using toybox 0.8.8, comm fails when trying to use stdin, e.g. `comm file1 - < file2` or `comm - file2 < file1`

it looks like the problem might be from switching xopenro to xfopen, which doesn't treat the file name "-" as anything special, and in fact if I have a file named - in the current directory, it will use that file instead of stdin.

**Comment by landley** [comment]
Try b5baa040128e

**Comment by mtboehlke** [comment]
Thanks!  This does resolve the issue I encountered.

I was wondering if `comm` should prevent both given files from being "-", but it seems other `comm`s will let you do it.  Any user trying it really shouldn't be expecting anything meaningful.
