### ISSUE TITLE
copy_file_range() doesn't work on all filesystems

### ISSUE THREAD

**Issue by git-bruh** [landley/toybox#382]
It seems like the `copy_file_range` syscall isn't guaranteed to work on all filesystems when copying to another filesystem, so `toybox cp` is basically broken:

```
openat(AT_FDCWD, "/usr/bin/gcc", O_RDONLY) = 3
openat(AT_FDCWD, "/tmp/gcc", O_RDWR|O_CREAT|O_TRUNC, 0100755) = 4
copy_file_range(3, NULL, 4, NULL, 1073741824, 0) = -1 EXDEV (Invalid cross-device link)
```

btrfs -> broken
ext4 -> broken
zfs -> works
nfs, fuse, cifs, ceph -> should work
... -> ...

The man-page doesn't cover this limitation, it only mentions it being supported after Linux 5.3, `EXDEV  The files referred to by fd_in and fd_out are not on the mounted filesystem (pre Linux 5.3).`

https://github.com/landley/toybox/blob/62f89088fdb1c63301b15ec3502fdf70990d17cd/lib/portability.c#L650

```
diff --git a/lib/portability.c b/lib/portability.c
index 7be909e..fa2ebe4 100644
--- a/lib/portability.c
+++ b/lib/portability.c
@@ -647,7 +647,13 @@ long long sendfile_len(int in, int out, long long bytes, long long *consumed)
       // Android's had the constant for years, but you'll get SIGSYS if you use
       // this system call before Android U (2023's release).
 #if defined(__NR_copy_file_range) && !defined(__ANDROID__)
-      len = syscall(__NR_copy_file_range, in, 0, out, 0, len, 0);
+      long long maybe_len = syscall(__NR_copy_file_range, in, 0, out, 0, len, 0);
+
+      if (maybe_len == -1 && errno == EXDEV) {
+          len = syscall(__NR_sendfile, out, in, NULL, len);
+      } else {
+          len = maybe_len;
+      }
 #else
       errno = EINVAL;
       len = -1;
```

**Comment by landley** [comment]
Commit 63f787b602f7 added a check for ENOSYS and now you're saying it can return EXDEV as well?

Sounds like the errno check is probably wrong and _any_ failure should trigger the fallback path.

**Comment by landley** [comment]
Try commit ff3f93a3bae6

**Comment by wael444** [comment]
i believe that commit has fixed it.
