### ISSUE TITLE
kbuild can't handle .config files with lines more than 1024 lines

### ISSUE THREAD

**Issue by trofi** [landley/toybox#384]
Filing the bug against `toybox` as it shares similar problem with `busybox`.

Bug originally reported by brothermechanic in https://github.com/trofi/nix-guix-gentoo/issues/22 against busybox-1.35.0.

There user's `.config` file contains this long line (exceeds 1K limit a bit):

> CONFIG_EXTRA_CFLAGS="-march=skylake -mmmx -mpopcnt -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx -mavx2 -mno-sse4a -mno-fma4 -mno-xop -mfma -mno-avx512f -mbmi -mbmi2 -maes -mpclmul -mno-avx512vl -mno-avx512bw -mno-avx512dq -mno-avx512cd -mno-avx512er -mno-avx512pf -mno-avx512vbmi -mno-avx512ifma -mno-avx5124vnniw -mno-avx5124fmaps -mno-avx512vpopcntdq -mno-avx512vbmi2 -mno-gfni -mno-vpclmulqdq -mno-avx512vnni -mno-avx512bitalg -mno-avx512bf16 -mno-avx512vp2intersect -mno-3dnow -madx -mabm -mno-cldemote -mclflushopt -mno-clwb -mno-clzero -mcx16 -mno-enqcmd -mf16c -mfsgsbase -mfxsr -mno-hle -msahf -mno-lwp -mlzcnt -mmovbe -mno-movdir64b -mno-movdiri -mno-mwaitx -mno-pconfig -mno-pku -mno-prefetchwt1 -mprfchw -mno-ptwrite -mno-rdpid -mrdrnd -mrdseed -mno-rtm -mno-serialize -msgx -mno-sha -mno-shstk -mno-tbm -mno-tsxldtrk -mno-vaes -mno-waitpkg -mno-wbnoinvd -mxsave -mxsavec -mxsaveopt -mxsaves -mno-amx-tile -mno-amx-int8 -mno-amx-bf16 -mno-uintr -mno-hreset -mno-kl -mno-widekl -mno-avxvnni --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=6144 -mtune=skylake -dumpbase null -O2 -pipe"

That renders the following:

    make oldconfig
    # using defaults found in .config
    #
    .config:52:warning: invalid string found
    .config:53:warning: unexpected data

Currently I'm working it around bu inflating the temporary buffer:

```diff
--- busybox-1.35.0.orig/scripts/kconfig/confdata.c      2021-12-26 16:53:21.000000000 +0000
+++ busybox-1.35.0/scripts/kconfig/confdata.c   2022-10-06 18:48:01.374687000 +0100
@@ -87,7 +87,7 @@
 int conf_read_simple(const char *name)
 {
        FILE *in = NULL;
-       char line[1024];
+       char line[64 * 1024];
        char *p, *p2;
        struct symbol *sym;
        int i;
```

Upstream kbuild fixed it in 2012: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=1a7a8c6fd8ca24d3692dacddf8d658c9bb9c14ad

Worth pulling equivalent of kernel's fix into `toybox` as well?

Thank you!

**Comment by landley** [comment]
Toybox doesn't channel toolchain stuff through kconfig? There's no CONFIG_EXTRA_CFLAGS entry in toybox's Config.in and friends. The only non-binary config entries we use are CONFIG_TOYBOX_UID_SYS=100 and CONFIG_TOYBOX_UID_USR=500

We have a todo item to throw away the old kernel derived kconfig and write a new one from scratch, but it hasn't made it near the top of the todo list yet.

**Comment by trofi** [comment]
Ah, I did not realize `.config` options differ so much. Let's close as INVALID. Apologies for the noise.
