### ISSUE TITLE
uninitialized variable `status` in `xwaitpid` and failed `waitpid()` call

### ISSUE THREAD

**Issue by jingyuanliang** [landley/toybox#389]
I'm building from source code tagged at 0.8.8 using clang. I've noticed a situation that `timeout` returns non-zero for a command that successfully returns.

I've traced the calls and found that in
https://github.com/landley/toybox/blob/61503984792cad62dc667693220dc06c8ccea362/lib/xwrap.c#L340-L347

* `status` is not initialized
* When `waitpid()` fails, `status` doesn't get set and remains uninitialized
* When `waitpid()` fails and `errno` is not `EINTR`, the code continues execution past `while` and reads from `status`

In my case, `waitpid()` leaves 10 in `errno` which is `ECHILD`. I didn't figure out the reason why it got `ECHILD`, but commit 6b78f8de9edab04b520e6c6ed39bf7b36021d146 fixed it, so it's likely the bad PID issue mentioned there.

For the record, the environment where I ran into this is an Alpine Linux AArch64 running in Docker on AMD64 with QEMU. The AArch64 binary is built with QEMU but will ultimately run natively on ARM in production. I didn't test to see if it's really broken on native ARM.

The bad pid issue in `timeout` is gone, but I'm not sure if we still need to address the issue that when `xwaitpid` gets a bad pid it reads from an uninitialized variable.

**Comment by jingyuanliang** [comment]
@enh-google

**Comment by jingyuanliang** [comment]
Hi @landley - by the way when will we get a newer version with a fix for the `timeout` bug?

**Comment by landley** [comment]
Try commit a83d1d59bf40

**Comment by landley** [comment]
Sigh, and now that _I've_ tested it, try commit 61daed9c2e1f

**Comment by jingyuanliang** [comment]
Thanks. This one looks good and I do see 127 returned when I run `timeout` without 6b78f8de9edab04b520e6c6ed39bf7b36021d146 patched.

Will we get a new release or should we cherry pick the fixes ourselves?

**Comment by landley** [comment]
Is the ball in my court on this one? (You need still need tar --wildcards but that's not a regression?)

**Comment by jingyuanliang** [comment]
I think all code changes are now done. I was considering if I should wait for 0.8.9 but I just ended up cherry-picking the patching commits to 0.8.8.

**Comment by landley** [comment]
Ah, I thought you were waiting for an Android resync.

Toybox project releases are approximately quarterly. Android pulls of toybox are approimately weekly, but can be delayed by internal testing. Looks like the most recent was on the 24th:
https://android.googlesource.com/platform/external/toybox/+/e87b8e5957bc

**Comment by jingyuanliang** [comment]
Uhm no, I'm not the Android team and I'm using your original source code / release tags.

Elected to use toybox seeing it trusted by Android team for years.
