### ISSUE TITLE
Group commands by function 

### ISSUE THREAD

**Issue by jidanni** [landley/toybox#398]
In http://landley.net/toybox/ we read 
> What commands are planned/implemented in toybox?
The current list of commands implemented by toybox is on the status page...

Okay. That's great. But it would still be great to have a additional list of all the commands grouped by their functionality:
- networking commands
- file status commands
- data manipulation commands
- etc.

**Comment by landley** [comment]
The subdirectories under "toys" in the source group the commands into posix, lsb (linux standard base), network, other, and pending. Those categories are the ones used by "make menuconfig" as submenus.

The roadmap.html page has a lot of categories of commans, which https://landley.net/toybox/status.html uses to categorize them when calculating completion status. (Well, that's the output page, scripts/mkstatus.py does the calculating.)

And at the end of the roadmap page, https://landley.net/toybox/roadmap.html#packages relates toybox commands to debian packages.

There's three different ways of grouping commands already, your complaint seems to be "that's not how I would have grouped them"? (Is there a command that _doesn't_ manipulate data? Even "true" and "false" produce a detectable output and are used to modify flow control in scripts...)

**Comment by jidanni** [comment]
https://perldoc.perl.org/perlfunc#Perl-Functions-by-Category was the model I was thinking of. But OK you already implemented it.
