### ISSUE TITLE
gunzip FILE, but output file is not complete

### ISSUE THREAD

**Issue by JinuineLi** [landley/toybox#402]
I have a file compressed to xxx.gz, through ZLIB I think, not gzip from toybox. 

size of xxx.gz is 277KB.

When decompressed in windows, the output file's size is 2351KB, which is as expected.

However, when I decompress xxx.gz througn gunzip of toybox, the output file  turns out to be incomplete, size is only 49KB, the decompression seems to stop at 49KB.

Is there something wrong about gunzip?

**Comment by JinuineLi** [comment]
what does 'final' mean? Is it part of GZIP format?

![image](https://user-images.githubusercontent.com/104982065/208843267-ed82104e-3298-4763-ab02-cfe8cf0077ce.png)

**Comment by landley** [comment]
Yes, it's in rfc 1951: https://www.ietf.org/rfc/rfc1951.txt#:~:text=BFINAL

"BFINAL is set if and only if this is the last block of the data set."

That said, zcat should be able to accept multiple concatenated zip files and treat them as one file, which isn't a thing I knew when I wrote it. You didn't attach a test case reproducing the issue, but let me see if I can reproduce it here...

**Comment by JinuineLi** [comment]
> Yes, it's in rfc 1951: https://www.ietf.org/rfc/rfc1951.txt#:~:text=BFINAL
> 
> "BFINAL is set if and only if this is the last block of the data set."
> 
> That said, zcat should be able to accept multiple concatenated zip files and treat them as one file, which isn't a thing I knew when I wrote it. You didn't attach a test case reproducing the issue, but let me see if I can reproduce it here...

sorry, I am writing from inside my company, can't send out any files. Only pictures is okay~

BUT, I added some log, 

I think that in decompress, or infalte process, It is trying to convert from huffman code to literbal symols. And it stops at dd->pos[50160], at the 2439th symbol. It corresponds to the output file's size. 

```
 50165 Dec 13 18:40  hilog_kmsg.001.19700122-114349
```

**What could possilbly caused this? Inflating stops early** 

![image](https://user-images.githubusercontent.com/104982065/208854906-2ee29a43-fc0e-407a-9b26-3a3d887718f8.png)

![image](https://user-images.githubusercontent.com/104982065/208855272-679b4b8c-bb4c-41ed-b505-0f42cd1a510d.png)

**Comment by landley** [comment]
256 is the end-of-block symbol. Again from the RFC:

https://www.ietf.org/rfc/rfc1951.txt#:~:text=end-of-block

**Comment by JinuineLi** [comment]
> mbol. Again from the RFC:

yes. So the issue left, gunzip(toybox) stops early, decoded an EOF symbol. Whereas by gunzip(Ubuntu) and windows, it runs till the end of the file.

**Comment by landley** [comment]
I've reproduced this, by the way:

$ cat <(echo hello | gzip) <(echo there | gzip) | zcat

with host zcat, shows both. With target zcat, just shows hello. I'll try to come up with a fix later today.

**Comment by JinuineLi** [comment]
Hi @landley , any progress with the fix :)
Apparently I tried continue instead of break the loop when EOF is decoded, and the decoding after that goes wrong :)

**Comment by landley** [comment]
Ah, sorry. Got distracted by family and the holidays.

The deflate plumbing buffers input data. Discarding the buffer it hasn't processed yet discards the next part of the file, so I need to change the internal API a bit to tell it how to resume with existing input.

Not a big deal, but not the 5 minute fix I originally thought.

**Comment by landley** [comment]
Try commit 8f8b49ffedde

**Comment by JinuineLi** [comment]
> Try commit [8f8b49f](https://github.com/landley/toybox/commit/8f8b49ffedde488df7d3e6ef690c69ec30bc8a9f)

Seems fixed, Thanks a lot :)
