### ISSUE TITLE
feature request: ls: --group-directories-first

### ISSUE THREAD

**Issue by apprehensions** [landley/toybox#404]
add a flag - or sort method, that sorts directorys first (hidden first, normal later).
this is similar to busybox's `--group-directories-first`, since by nature this makes more sense.

**Comment by landley** [comment]
Commit 25d72febcc2f

**Comment by landley** [comment]
In the absence of a complaint, I'm assuming this is fixed for you...

**Comment by apprehensions** [comment]
Sorry, I am not using toybox at the moment, but thank you!
