### ISSUE TITLE
sed substitute regression 

### ISSUE THREAD

**Issue by johnli360** [landley/toybox#411]
Running the following command in the repo root on the 0.8.0 tag:

`make defconfig && make && echo "012345" | ./toybox sed 's/./&X/4'`

outputs: `0123X45`, which matches the output of my locally installed GNU sed 4.8 binary ,
but the same command on later version tags either segfaults or outputs: `3X45` . Seems like commit `9f781cd5c3f7b071a3d9a62bf0a4aeb8c3cda8ec` introduced the segfault

**Comment by landley** [comment]
Reproduced, and I see what's happening. Object lifetime rules are wrong, need to think a bit to fix it.

**Comment by landley** [comment]
Try commit abd8b1b2215b

**Comment by johnli360** [comment]
Seems to work. Thanks!
