### ISSUE TITLE
UTF-8 character support in Android's `sed`

### ISSUE THREAD

**Issue by nooriro** [landley/toybox#430]
Consider the Unicode string `aα가😀`.

|Char|Code point|UTF-8 encoding|UTF-16 encoding|
|----|-----------|------------|-------------|
|`a`|`U+0061`|`61`|`0061`|
|`α`|`U+03B1`|`CE B1`|`03B1`|
|`가`|`U+AC00`|`EA B0 80`|`AC00`|
|`😀`|`U+1F600`|`F0 9F 98 80`|`D83D DE00`|

In Android's shell (`mksh`) it works well to print the string as it is.
```console
$ echo $'aα\uAC00\xF0\x9F\x98\x80' | tee /dev/stderr | xxd -g 1
aα가😀
00000000: 61 ce b1 ea b0 80 f0 9f 98 80 0a                 a..........
$
```
But applying `sed 's/./&|/g'` does not work as expected.
```console
$ echo $'aα\uAC00\xF0\x9F\x98\x80' | sed 's/./&|/g' | tee /dev/stderr | xxd -g 1
a|�|�|�|�|�|�|�|�|�|
00000000: 61 7c ce 7c b1 7c ea 7c b0 7c 80 7c f0 7c 9f 7c  a|.|.|.|.|.|.|.|
00000010: 98 7c 80 7c 0a                                   .|.|.
$
```

The metacharacter `.` matches **any single byte,** not any single character. \
I got this unexpected result on both \
\- Android 10 (`QQ3A.200805.001` on Pixel 3 XL; `toybox 0.8.0-android`) and \
\- Android 11 (`RQ1A.210205.004` on Pixel 4a; `toybox 0.8.3-android`).

Setting `LANG`/`LC_CTYPE`/`LC_ALL` to `C.UTF-8` didn't work on Android 10/11.
```console
$ echo $'aα\uAC00\xF0\x9F\x98\x80' | LANG=C.UTF-8 sed 's/./&|/g' | tee /dev/stderr | xxd -g 1
a|�|�|�|�|�|�|�|�|�|
00000000: 61 7c ce 7c b1 7c ea 7c b0 7c 80 7c f0 7c 9f 7c  a|.|.|.|.|.|.|.|
00000010: 98 7c 80 7c 0a                                   .|.|.
$ echo $'aα\uAC00\xF0\x9F\x98\x80' | LC_CTYPE=C.UTF-8 sed 's/./&|/g' | tee /dev/stderr | xxd -g 1
a|�|�|�|�|�|�|�|�|�|
00000000: 61 7c ce 7c b1 7c ea 7c b0 7c 80 7c f0 7c 9f 7c  a|.|.|.|.|.|.|.|
00000010: 98 7c 80 7c 0a                                   .|.|.
$ echo $'aα\uAC00\xF0\x9F\x98\x80' | LC_ALL=C.UTF-8 sed 's/./&|/g' | tee /dev/stderr | xxd -g 1
a|�|�|�|�|�|�|�|�|�|
00000000: 61 7c ce 7c b1 7c ea 7c b0 7c 80 7c f0 7c 9f 7c  a|.|.|.|.|.|.|.|
00000010: 98 7c 80 7c 0a                                   .|.|.
$
```

The expected result is as follows (the result on Ubuntu 20.04 on WSL1):
```console
$ echo $'aα\uAC00\xF0\x9F\x98\x80' | sed 's/./&|/g' | tee /dev/stderr | xxd -g 1
a|α|가|😀|
00000000: 61 7c ce b1 7c ea b0 80 7c f0 9f 98 80 7c 0a     a|..|...|....|.
$
```

How can I make `.` match each single UTF-8 character in Android's `sed`?

**Comment by landley** [comment]
This isn't really a sed issue, this is a libc issue: the regcomp(3)/regexec(3) implementation in bionic is byte based, so the "." wildcard isn't matching unicode characters. We call regexec() (sed.c line 478 calls regexec0() out of lib/lib.c which calls regexec() on line 1407) and it returns the length of the match (and any parenthetical sub-matches).

Unicode matching is actually a bit complicated, because what . should probably match is the next printable character AND any trailing unicode combining characters (because, as the name says, they combine).

(Unicode is terribly designed, you can't tell when you're done parsing unicode until you overshoot and have to back up. What single character wildcard should do if the next match is the "change direction" control sequence, I couldn't tell you. :)

I'm writing my own glob(3) implementation as part of sh.c (because I don't trust libc to have the bash extensions for +() and such), but I'm using the libc regex implementation in glibc, musl, and bionic.

**Comment by nooriro** [comment]
@landley Thanks for the explanation.

I don't know much about the C language, but I looked at the change history of `bionic`'s `regexec.c` file in the link below.\
<https://github.com/aosp-mirror/platform_bionic/commits/master/libc/upstream-netbsd/lib/libc/regex/regexec.c>

Before commit `88e4e60` on November 8, 2022, it seems that there was no code to support multibyte at all (only [`SNAMES`](https://github.com/aosp-mirror/platform_bionic/blob/677b6e605be95f434602f19a627ea0dea2927ccd/libc/upstream-netbsd/lib/libc/regex/regexec.c#L108-L133) and [`LNAMES`](https://github.com/aosp-mirror/platform_bionic/blob/677b6e605be95f434602f19a627ea0dea2927ccd/libc/upstream-netbsd/lib/libc/regex/regexec.c#L135-L185) macros.)\
With commit `88e4e60`, [the `MNAMES` macro was added](https://github.com/aosp-mirror/platform_bionic/blob/88e4e60a75841db476b765742ea61fc0403abbed/libc/upstream-netbsd/lib/libc/regex/regexec.c#L200-L208).\
I don't know whether `bionic`'s `regexec()` function will or will not support multibyte characters on future versions of Android.

Anyway, it's **sad** that even on Android versions **released in the 2020s**, the built-in `sed` command doesn't support UTF-8 characters.

While looking for a solution to this problem, I noticed that there are [official prebuilt binaries](https://landley.net/toybox/downloads/binaries/latest/) of toybox, which is **statically linked against `musl-libc`** and **runs on Android.** (via [this comment](https://github.com/landley/toybox/issues/335#issuecomment-1111689430) on issue #335)
I downloaded `toybox-aarch64` and ran it as shown below, and it worked as expected. :)
```batchfile
adb push %USERPROFILE%\Downloads\toybox-aarch64 /data/local/tmp/
adb shell
```
```console
$ cd /data/local/tmp
$ ls -l toybox-aarch64
-rw-rw-rw- 1 shell shell 825176 2023-05-17 02:52 toybox-aarch64
$ chmod u+x toybox-aarch64
$ ./toybox-aarch64 --version
toybox 0.8.9
$ echo $'aα\uAC00\xF0\x9F\x98\x80' | ./toybox-aarch64 sed 's/./&|/g' | tee /dev/stderr | xxd -g 1
a|α|가|😀|
00000000: 61 7c ce b1 7c ea b0 80 7c f0 9f 98 80 7c 0a     a|..|...|....|.
$ exit
```
(Tested on: Pixel 3 XL with Android 10 `QQ3A.200805.001` / Windows 10 22H2 `19045.2965` / Windows Terminal 1.16.10261.0)

**Comment by landley** [comment]
The static prebuilt binaries are built against musl-libc, which has a different regex implementation.

**Comment by nooriro** [comment]
> The lack of utf8 support in toybox sed is either a packaging/deployment decision on Android's part, or it's a feature decision on bionic libc's part.

I got this, so I was wondering if there might be a comment from @enh-google on this issue.
