### ISSUE TITLE
`kill` command shouldn't assume process name has no spaces in it

### ISSUE THREAD

**Issue by pigboysid** [landley/toybox#433]
In [kill.c](https://github.com/landley/toybox/blob/master/toys/posix/kill.c#L121), this line scans through the first 6 columns of `/proc/<pid>/stat` to find `procsid`:

          if (sscanf(toybuf, "%*d %*s %*c %*d %*d %d", &procsid) != 1) continue;

The 2nd column (which is skipped using `%*s`) contains the name of the running process enclosed in parentheses. As a real world example, here's how the first 6 columns of `/proc/2021132/stat` might look for an executable named `myexec`:

    2021132 (myexec) R 1491839 2021132 1491839

In that case, `procsid` would contain 1491839 after the `sscanf` is run.

However, it's possible for the executable name to have whitespace (and also parentheses) in it. A (contrived) real world example for a process called `myexec (tb) xyz` might have this data in `/proc/2021132/stat`:

    2021132 (myexec (tb) xyz) R 1491839 2021132 1491839

In that case, the `sscanf` as written will fail.

A fix is to use `strrchr` to scan `toybuf` for the final closing parenthesis in the line, and then to the `sscanf` from there. A `diff`-style example of the patch is:

      int count, procpid, procsid;
     +char *closing_paren;

      if (!(procpid = atoi(entry->d_name))) continue;

      snprintf(toybuf, sizeof(toybuf), "/proc/%d/stat", procpid);
      if (!readfile(toybuf, toybuf, sizeof(toybuf))) continue;
     +if (!(closing_paren = strrchr(toybuf, ')')) continue;
     -if (sscanf(toybuf, "%*d %*s %*c %*d %*d %d", &procsid) != 1) continue;
     +if (sscanf(closing_paren + 1, " %*c %*d %*d %d", &procsid) != 1) continue;

Would you like me write the patch and submit a PR?

**Comment by landley** [comment]
Try commit af055dabfc90

(Did it on an airplane yesterday, couldn't reply at the time.)

**Comment by pigboysid** [comment]
Yep that fix looks good. Thanks!
