### ISSUE TITLE
cpio does not support -L / --dereference

### ISSUE THREAD

**Issue by jacky8hyf** [landley/toybox#434]
Repro script

```
mkdir /tmp/foo
cd /tmp/foo
touch x
ln -sf x y
echo "y" | cpio --quiet -d -p -L /tmp/bar
```

Expected:
`/tmp/bar/y` exists as a regular file

Actual:
```
cpio: Unknown option 'L' (see "cpio --help")
```

Could you please add support of --dereference / -L to cpio? Thank you!

**Comment by landley** [comment]
Commit 57f85a153ebb

**Comment by jacky8hyf** [comment]
Thank you! I have verified that this issue is fixed.
