### ISSUE TITLE
bunzip2 deletes files on error

### ISSUE THREAD

**Issue by 251** [landley/toybox#436]
E.g.:
```bash
$ printf '\x00' > A
$ toybox-0.8.9/bin/toybox bunzip2 A
bunzip2: not bzip
bunzip2: A: No such file or directory
```
`A` is gone afterwards.

**Comment by landley** [comment]
Sigh, some of the error paths error_exit() and others return to do the cleanup, so if you touch the file you won't see it but if you echo one byte to it you do...

**Comment by landley** [comment]
Try commit 0ff69e539fc7

**Comment by 251** [comment]
Seems to work now, thanks.
