### ISSUE TITLE
date: segfault with `-s+`

### ISSUE THREAD

**Issue by 251** [landley/toybox#437]
`$ toybox-0.8.9/bin/toybox date "-s+"`

Results in a NULL pointer in `puts_time`:
`puts_time (fmt=0x1 <error: Cannot access memory at address 0x1>, tm=0x7ffff7ea76a0 <_tmbuf>) at toys/posix/date.c:102`

(found by KLEE)

**Comment by landley** [comment]
Sorry for the delay (dental surgery). Try commit 369526ea9a50

**Comment by 251** [comment]
Seems to work, thanks!
