### ISSUE TITLE
"grep -A -m" missing lines on last match

### ISSUE THREAD

**Issue by renaatd** [landley/toybox#439]
"grep -A1" shows correctly one extra line after a match and "grep -m1" stops correctly after one match. But the combination "grep -A1 -m1" doesn't show the extra line after the match. For higher values of the parameter m: the last match doesn't has the extra lines.

Input file:
```
match 
1
match
2
match
3
```

Command: "grep -A1 -m2 match my_file"
Expected output (also output of GNU grep):
```
match
1
match
2
```
Actual output:
```
match
1
match
```
Tested on latest master branch

**Comment by landley** [comment]
Try commit 4277f1801036

**Comment by renaatd** [comment]
Now grep works as expected. Thanks!
