### ISSUE TITLE
stat does not resolve GUID or UID on Android

### ISSUE THREAD

**Issue by d4rken** [landley/toybox#44]
Just to track known issues, came up in #36

It works using the stock toybox that ships with Android 6.0.1 on the Nexus5 (--version shows c96e42498c99-android):

```
root@hammerhead:/sdcard # stat -c "%G" twrp-3.0.0-0-hammerhead.img
    root
root@hammerhead:/sdcard # stat -c "%U" twrp-3.0.0-0-hammerhead.img
    root
```

[According to @landley](https://github.com/landley/toybox/issues/36#issuecomment-239650915) this is not a toolchain issue and already a work in progress.

**Comment by enh** [comment]
close?

**Comment by enh** [comment]
specifically, fixed by https://github.com/landley/toybox/commit/1a429a722a504f0cdf3ffb90a331eb3f55deee5a
