### ISSUE TITLE
ls '-k' option is in the help but not supported

### ISSUE THREAD

**Issue by dlegaultbbry** [landley/toybox#449]
I can see the letter in the usage line (https://github.com/landley/toybox/blob/master/toys/posix/ls.c#L17) and there's a comment about it in in the help text that it is ignored and couldn't find it referenced in the code. I also see the recent block-size option change which basically overrides this entirely.

I can send a PR request, if this is ok with you, to cleanup the help menu.

**Comment by enh-google** [comment]
my guess is that this is another instance of rob's "don't document no-op arguments". but, yeah, there should probably be a change to the USE line to make it clear that -k and the block size argument are mutually exclusive?

**Comment by dlegaultbbry** [comment]
I guess you are right. On QNX we default to 512 because that's what the system does so I guess I'll have to wedge in some code to set the value to blocksize value to 1024 if you specify -k because it won't be a silent/noop option anymore for our system. I'll wait for the next release to have the blocksize change and adapt. Thanks.

**Comment by landley** [comment]
http://lists.landley.net/pipermail/toybox-landley.net/2023-August/029681.html
