### ISSUE TITLE
Implement -execdir for safety and security

### ISSUE THREAD

**Issue by mcandre** [landley/toybox#476]
The popular BSD and GNU implementations of findutils implement an `-execdir` flag on find, which provides more accurate exit code information (`-exec` implicitly drops failing codes on the floor).

https://www.gnu.org/software/findutils/manual/html_mono/find.html#Conclusion

Can toybox find please implement this flag, too?

Some larger operating systems like Alpine Linux default their find implementation to toybox's, with deleterious results unless the GNU findutils package is installed, overriding the default.

**Comment by landley** [comment]
We have execdir already. Are you saying it doesn't work?

When did Alpine Linux start defaulting to toybox find? I thought they used busybox?

**Comment by mcandre** [comment]
Oh, good to hear!

I can't remember whether Alpine uses toybox or busybox. Maybe the solution
for Alpine is as simple as updating the version they consume.
