### ISSUE TITLE
Test applet NOT operator issues

### ISSUE THREAD

**Issue by d4rken** [landley/toybox#48]
The `int not` is [never initliazed](https://github.com/d4rken/toybox/blob/a6b99efdebc9df9d6b8b8ef3472fc2cb733d4694/toys/pending/test.c#L44) but still applied [at the end](https://github.com/d4rken/toybox/blob/a6b99efdebc9df9d6b8b8ef3472fc2cb733d4694/toys/pending/test.c#L112) of the function to the exitvalue.

Also:
If the file does not exist the `!` operator is [never applied](https://github.com/d4rken/toybox/blob/a6b99efdebc9df9d6b8b8ef3472fc2cb733d4694/toys/pending/test.c#L63) to the exitvalue.

(I submitted this issue to the mailing list. But I think having open issues for "TODO stuff " here is good, even if discussion on the mailing list is preferred.)

**Comment by enh-google** [comment]
obsoleted by test.c rewrite. (if you have a specific example that still doesn't work, let us know.)
