### ISSUE TITLE
xargs has non-conforming behavior (failing to exit) when a child exits with exit status 255

### ISSUE THREAD

**Issue by GabrielRavier** [landley/toybox#483]
An invocation of `xargs` such as `echo $(seq 1 100) | ./toybox-x86_64 xargs -n1 sh -c 'sleep "$0"; echo "$0"; exit 255'` results in the following:

```bash
$ echo $(seq 1 6) | ./toybox-x86_64 xargs -n1 sh -c 'sleep "$0"; echo "$0"; exit 255'
1
xargs: sh: exited with status 255; aborting
2
xargs: sh: exited with status 255; aborting
3
xargs: sh: exited with status 255; aborting
4
xargs: sh: exited with status 255; aborting
5
xargs: sh: exited with status 255; aborting
6
xargs: sh: exited with status 255; aborting
$ echo $?
124
$ 
```

even though the POSIX standard states that:

> If [...] an invocation of the utility exits with exit status 255, the xargs utility shall write a diagnostic message **_and exit without processing any remaining input._**

...meaning that Toybox should have exited after printing the first diagnostic, without processing the rest of the input.

**Comment by landley** [comment]
Assuming in the absence of objection that the above commit fixed it.

**Comment by GabrielRavier** [comment]
Can confirm it seems fixed on my end too.
