### ISSUE TITLE
getty: does not display issue

### ISSUE THREAD

**Issue by mtboehlke** [landley/toybox#508]
`getty` does not display /etc/issue, regardless of whether `-i` is specified or not.  The login prompt is still displayed.  I noticed this after upgrading to 0.8.11.

A quick git bisect seems to indicate this was introduced in 3e0e8c687eee4c292db106efab20f8e565549bf8.

**Comment by enh-google** [comment]
fix sent to list: http://lists.landley.net/pipermail/toybox-landley.net/2024-August/030480.html
