### ISSUE TITLE
command unshare broken

### ISSUE THREAD

**Issue by Jacobw1oo** [landley/toybox#511]
Toybox 0.8.9-android multicall binary, i am rooted user, and the unshare command refuses to work. 
Tested commands 
unshare --user --pid --map-root-user --fork bash 
unshare: Invalid argument
NX729J-EEA:/ # toybox unshare --fork bash                                                                                                                    
works
NX729J-EEA:/ # toybox unshare --ipc --fork bash                                                                                                              
unshare: Invalid argument
1|NX729J-EEA:/ # toybox unshare --pid --fork bash                                                                                                            
unshare: Invalid argument
1|NX729J-EEA:/ # toybox unshare --uts --fork bash                                                                                                            
works
NX729J-EEA:/ # toybox unshare --user --fork bash                                                                                                             
unshare: Invalid argument
All of these commands work on AMD64 Arch Linux
is there anything i can do to update or fix this command?

**Comment by enh-google** [comment]
i think that just means your kernel was compiled without those options. see the ERRORS section of https://man7.org/linux/man-pages/man2/unshare.2.html for details.
