### ISSUE TITLE
gcc14: toys/pending/mke2fs.c:345:23: error: passing argument 1 of 'same_file' from incompatible pointer type [-Wincompatible-pointer-types]

### ISSUE THREAD

**Issue by vt-alt** [landley/toybox#531]
There is build errors on [gcc14](https://gcc.gnu.org/gcc-14/porting_to.html) (14.2.1):
```
musl-gcc -I/etc/sysconfig/kernel/include -pipe -frecord-gcc-switches -Wall -fdiagnostics-color=always -g -O2 -flto=auto -Wall -Wundef -Werror=implicit-function-declaration -Wno-char-subscripts -Wno-pointer-sign -funsigned-char -Wno-restrict -Wno-format-overflow -I . -Os -ffunction-sections -fdata-sections -fno-asynchronous-unwind-tables -fno-strict-aliasing -c toys/pending/vi.c -o generated/obj/vi.o
toys/pending/mke2fs.c: In function 'check_treelinks':
toys/pending/mke2fs.c:345:23: error: passing argument 1 of 'same_file' from incompatible pointer type [-Wincompatible-pointer-types]
  345 |         if (same_file(current, that)) {
      |                       ^~~~~~~
      |                       |
      |                       struct dirtree *
In file included from ./toys.h:71,
                 from toys/pending/mke2fs.c:75:
./lib/lib.h:235:28: note: expected 'struct stat *' but argument is of type 'struct dirtree *'
  235 | int same_file(struct stat *st1, struct stat *st2);
      |               ~~~~~~~~~~~~~^~~
toys/pending/mke2fs.c:345:32: error: passing argument 2 of 'same_file' from incompatible pointer type [-Wincompatible-pointer-types]
  345 |         if (same_file(current, that)) {
      |                                ^~~~
      |                                |
      |                                struct dirtree *
./lib/lib.h:235:46: note: expected 'struct stat *' but argument is of type 'struct dirtree *'
  235 | int same_file(struct stat *st1, struct stat *st2);
      |                                 ~~~~~~~~~~~~~^~~
```
Tested on x86-64 `master` branch.

**Comment by landley** [comment]
On 11/30/24 06:49, Vitalio wrote:
> There is build errors on gcc14 (14.2.1):
> ```
> musl-gcc -I/etc/sysconfig/kernel/include -pipe -frecord-gcc-switches -Wall -fdiagnostics-color=always -g -O2 -flto=auto -Wall -Wundef -Werror=implicit-function-declaration -Wno-char-subscripts -Wno-pointer-sign -funsigned-char -Wno-restrict -Wno-format-overflow -I . -Os -ffunction-sections -fdata-sections -fno-asynchronous-unwind-tables -fno-strict-aliasing -c toys/pending/vi.c -o generated/obj/vi.o
> toys/pending/mke2fs.c: In function 'check_treelinks':
> toys/pending/mke2fs.c:345:23: error: passing argument 1 of 'same_file' from incompatible pointer type [-Wincompatible-pointer-types]

There's a reason it's in pending. (It doesn't do anything, it's a 
half-finished command from years ago, I never got back to it...) As the 
README and web page and so on say, start with "defconfig" not 
"allyesconfig" (unless you REALLY know what you're doing).

But how did -Werror=implicit-funciton-declaration turn into a global 
-Werror rather than a warning? That sounds like a gcc14 bug: "error: 
passing argument 1" should be "warning". (Should I add a test for gcc 14 
in portability.sh to add a -Wno-error to work around their bug?)

**Comment by vt-alt** [comment]
At first I enabled as many commands as possible in case people find it useful by default (to debug boot or docker, and people report they do). Then I do `silentoldconfig` updates. Perhaps, I should disable `CONFIG_MKE2FS` if it isn't even partially useful. But it sounded useful, as many other pending toys do.

> That sounds like a gcc14 bug

Yes this is intentional feature of gcc14.

> (Should I add a test for gcc 14 in portability.sh to add a -Wno-error to work around their bug?)

Or just change the code so such workarounds aren't needed.

**Comment by enh-google** [comment]
> But how did -Werror=implicit-funciton-declaration turn into a global
> -Werror rather than a warning? That sounds like a gcc14 bug: "error: 
> passing argument 1" should be "warning".

because it's one of the breaking changes in C23 relative to C17. (i know this because i've had to go through the entire Android code base fixing this.)

> (Should I add a test for gcc 14
> in portability.sh to add a -Wno-error to work around their bug?)

gcc 14 is probably just the first gcc that defaults to C23. the right fix is to add a `-std=gnu17` to stay where you are (or `-std=gnu11` if that's your intended target).

**Comment by enh-google** [comment]
(or, obviously, just fix things to work with C23 too --- in all of Android i haven't found anything where you can't be compatible with everything. fwiw, the bits of toybox that Android builds are all C23 compatible.)

**Comment by landley** [comment]
Commit 6b02f029150f

**Comment by vt-alt** [comment]
Thank you.
