### ISSUE TITLE
Toybox printf is printing incorrect hex values

### ISSUE THREAD

**Issue by sandeep-mvd** [landley/toybox#54]
printf of an hex value is printing strange values. Please see the below code
```
root:/ # printf "%x\n" 100
300000078
```
64 is expected but it prints strange values.

I am working in android environment. printf in android env uses printf of toybox.

```
root:/ # which printf
/system/bin/printf
root:/ # ls -l /system/bin/printf
lrwxr-xr-x root     shell             2016-11-14 21:02 printf -> toybox
```

If this issue is already fixed, please tell the corresponding patch.

**Comment by landley** [comment]
On 11/17/2016 09:39 PM, Sandeep Kumar wrote:
> I am working in android environment.
> printf of an hex value is print string values. Please see the below code
> 
> |root:/ # printf "%x\n" 100 300000078 |
> 
> 64 is expected but it prints strange values.

I'm getting 64 here... ah, that's what I'm getting with 64-bit glibc.
With 32-bit musl I get:

$ ./printf '%x\n' 100
80539a100000064

Which is very much not right. Hmmm... Ah! printf("%llx", (long)blah);

Fixed. Sorry about that,

Rob

**Comment by sandeep-mvd** [comment]
Thank you for the fix.
I am cherry-picking this patch. Thank you.
 https://github.com/landley/toybox/commit/46ae1aaea845d4ea3e1cd2b3e005fdb6a6428053

**Comment by sandeep-mvd** [comment]
I have confirmed it. This patch fixes the issue
```
root:/ # printf "%x\n" 100                                          
64
```

Thank you once again.

**Comment by enh** [comment]
sandeep: mark as closed?
