### ISSUE TITLE
When compiling toybox as shared lib it is not loading with LD_PRELOAD

### ISSUE THREAD

**Issue by IgalGokhman** [landley/toybox#63]
The following error is thrown when toybox is compiled with -fPIC -shared and run from LD_PRELOAD on android (tested on Samsung S7 nougat)
CANNOT LINK EXECUTABLE [snip] library "libgcc_s.so.1" not found

**Comment by enh-google** [comment]
> "libgcc_s.so.1"

that looks like you're trying to run a *desktop* (glibc) binary on Android. that's unlikely to work. you'll need to compile with the NDK against bionic instead.
