### ISSUE TITLE
Code of Conduct link have been moved.

### ISSUE THREAD

**Issue by theel0ja** [landley/toybox#68]
The old link: https://engineering.twitter.com/opensource/code-of-conduct (can be found from README file)
The new link: https://github.com/twitter/code-of-conduct/blob/master/code-of-conduct.md

**Comment by landley** [comment]
On 06/11/2017 04:17 AM, Elias Ojala wrote:
> The old link: https://engineering.twitter.com/opensource/code-of-conduct
> (can be found from README file)
> The new link:
> https://github.com/twitter/code-of-conduct/blob/master/code-of-conduct.md

Hmmm, I'm not declaring a git repo to be toybox policy. (If they think
it's going to change often enough to need version tracking, I'm dubious.)

I fished the old one out of archive.org and mirrored it on the website
(it's CC with attribution but the link to their git repo at the bottom
should cover that). And move the link to it from the README to the nav bar.

Thanks for the heads up,

Rob

**Comment by enh** [comment]
fixed by https://github.com/landley/toybox/commit/bc308973ffb671084328da6e20f146cba1454466 and can be closed.

**Comment by theel0ja** [comment]
Closing.
