### ISSUE TITLE
toybox ps give out a segment fault

### ISSUE THREAD

**Issue by butterl** [landley/toybox#74]
Hi， 

we have meet ps  segment fault while doing test 
```
pid: 6149, tid: 6149, name: ps  >>> /system/bin/ps <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10
Cause: null pointer dereference

Stack Trace:
  RELADDR           FUNCTION                     FILE:LINE
  0000000000034294  get_threads+228              external/toybox/toys/posix/ps.c:917
  000000000000da2c  dirtree_handle_callback+36   external/toybox/lib/dirtree.c:112
  000000000000db38  dirtree_recurse+128          external/toybox/lib/dirtree.c:156
  000000000000da84  dirtree_handle_callback+124  external/toybox/lib/dirtree.c:115
  0000000000033628  ps_main+952                  external/toybox/toys/posix/ps.c:1238
  000000000001375c  toy_exec+104                 external/toybox/main.c:166
  000000000001330c  toybox_main+48               external/toybox/main.c:179
  0000000000013818  main+124                     external/toybox/main.c:237
```

The ERROR code suspected as blow in get_threads, while in multi-thread , passing the parameters of the process is still running, the upper layer is not stopped, and ran to this function may have been out of the process, the marked code, will lead to access to empty pointers, causing crashes.
 
I also find some one has reported similar question in [mailing list ](https://www.mail-archive.com/toybox@lists.landley.net/msg03985.html)

Do you got any solution to this？

```
/ Recurse down into tasks, retaining thread groups.
// Disable show_process at least until we can calculate tcount
kcount = TT.kcount;
sprintf(toybuf, "/proc/%u/task", pid);
new->child = dirtree_flagread(toybuf, DIRTREE_SHUTUP|DIRTREE_PROC, get_ps);  ///////<<<<< suspected
if (new->child == DIRTREE_ABORTVAL) new->child = 0;  ///////<<<<< suspected
TT.threadparent = 0;
kcount = TT.kcount-kcount+1;
tb = (void *)new->extra;
tb->slot[SLOT_tcount] = kcount;
 
// Fill out tid and thread count for each entry in group
if (new->child) for (dt = new->child->child; dt; dt = dt->next) {
  tb = (void *)dt->extra;
  tb->slot[SLOT_pid] = pid;
  tb->slot[SLOT_tcount] = kcount;
}
 
// Save or display
if (!TT.show_process) return DIRTREE_SAVE;
TT.show_process((void *)new->extra);
dt = new->child;              ///////<<<<< suspected
new->child = 0;               ///////<<<<< suspected
while (dt->child) {            ///////<<<<< suspected
  new = dt->child->next;
  TT.show_process((void *)dt->child->extra);
  free(dt->child);
  dt->child = new;
}
free(dt);
```

**Comment by landley** [comment]
On 08/22/2017 07:16 AM, butterl wrote:
> Hi，
> 
> we have meet ps segment fault while doing test
> 
> |pid: 6149, tid: 6149, name: ps >>> /system/bin/ps <<< signal 11
> (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10 Cause: null pointer
> dereference Stack Trace: RELADDR FUNCTION FILE:LINE 0000000000034294
> get_threads+228 external/toybox/toys/posix/ps.c:917 000000000000da2c
> dirtree_handle_callback+36 external/toybox/lib/dirtree.c:112
> 000000000000db38 dirtree_recurse+128 external/toybox/lib/dirtree.c:156
> 000000000000da84 dirtree_handle_callback+124
> external/toybox/lib/dirtree.c:115 0000000000033628 ps_main+952
> external/toybox/toys/posix/ps.c:1238 000000000001375c toy_exec+104
> external/toybox/main.c:166 000000000001330c toybox_main+48
> external/toybox/main.c:179 0000000000013818 main+124
> external/toybox/main.c:237 |
> 
> The ERROR code suspected as blow in get_threads, while in multi-thread ,
> passing the parameters of the process is still running, the upper layer
> is not stopped, and ran to this function may have been out of the
> process, the marked code, will lead to access to empty pointers, causing
> crashes.
> 
> I also find some one has reported similar question in mailing list
> <https://www.mail-archive.com/toybox@lists.landley.net/msg03985.html>

Yes, and the fix to that was commit e97aeb6dea6e back in march, which
was in the 0.7.4 release in June.

> Do you got any solution to this？

What version are you running? Can you reproduce the issue against the
current tree?

Rob

**Comment by butterl** [comment]
Hi Rob， 

The patch already in the build tree,
the error seems here , 

```
if (new->child == DIRTREE_ABORTVAL) new->child = 0;  ///////<<<<< suspected
....
dt = new->child;              ///////<<<<< dt maybe 0 
while (dt->child) {            ///////<<<<< suspected
  new = dt->child->next;
  TT.show_process((void *)dt->child->extra);
  free(dt->child);
  dt->child = new;
}
```

**Comment by enh** [comment]
> Yes, and the fix to that was commit e97aeb6 back in march

the linked-to mailing list post was from me, reporting that although e97aeb6 reduced the incidence of this down to where i'm not aware of any human seeing ps crashes directly, we're still seeing occasional ones from automated crash reporting.

this is definitely still reproduceable. (as is top crashing if you leave it running long enough; this can be caught in reasonable-ish time frames if you run an asan build rather than a regular build, so it catches the corruption immediately. i've no idea whether these are related, so default to assuming they're not.)

**Comment by landley** [comment]
On 08/27/2017 02:25 PM, Elliott Hughes wrote:
>     Yes, and the fix to that was commit e97aeb6
>     <https://github.com/landley/toybox/commit/e97aeb6dea6ed654d599527c1f1d521e576743b4>
>     back in march
> 
> the linked-to mailing list post was from me, reporting that although
> e97aeb6
> <https://github.com/landley/toybox/commit/e97aeb6dea6ed654d599527c1f1d521e576743b4>
> reduced the incidence of this down to where i'm not aware of any human
> seeing ps crashes directly, we're still seeing occasional ones from
> automated crash reporting.

He replied and clarified, and I have a window open to remind me to fix it.

Sorry, between the hurricane and $DAYJOB still being in crunch mode the
time I thought I'd spend on toybox this weekend's been mostly eaten by
other things. Lemme try to catch up...

> this is definitely still reproduceable. (as is top crashing if you leave
> it running long enough; this can be caught in reasonable-ish time frames
> if you run an asan build rather than a regular build, so it catches the
> corruption immediately. i've no idea whether these are related, so
> default to assuming they're not.)

Nah, I'm pretty sure it's a null pointer dereference. Hits the guard
page, crashes on anything with an mmu. :)

Sorry for the slow response...

Rob

**Comment by butterl** [comment]
Hi Rob, 

Seems this race condition will not fix with a simple nullptr checker workaround , do you got any good idea on this?

BRs,
Chao

**Comment by raymond-wx** [comment]
@landley  
Hi Rob, 
we also met this issue in our autotest pipe line many times,  if this issue get fixed we can avoid lots of noise from autotest pipe.

**Comment by enh** [comment]
another instance today from automated testing:

```
pid: 29772, tid: 29772, name: ps  >>> ps <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10
x0   0000000000000000  x1   0000000000000000  x2   0000000000000000  x3   0000007ff72069a8
x4   0000007c072d17e7  x5   0000007c0721d07e  x6   0000000000000069  x7   0000000000000070
x8   0000000000000000  x9   0000000000000001  x10  0000000000004001  x11  0000000000000000
x12  0000007c076d04b0  x13  00000000fffffffe  x14  0000000000000001  x15  0000000000000002
x16  0000007c076ee2c8  x17  0000007c0768bad8  x18  0000007c076f9000  x19  0000007c072350c0
x20  0000000000000000  x21  000000556ae34868  x22  000000556ae31840  x23  00000000000008c5
x24  0000007c07235010  x25  0000000000000000  x26  0000000000000000  x27  0000000000000000
x28  0000000000000000  x29  0000007ff72071a0  x30  000000556ae06f98
sp   0000007ff7207170  pc   000000556ae06fa0  pstate 0000000080000000

Stack Trace:
  RELADDR           FUNCTION                     FILE:LINE
  0000000000036fa0  get_threads+228              external/toybox/toys/posix/ps.c:920
  000000000000db9c  dirtree_handle_callback+36   external/toybox/lib/dirtree.c:112
  000000000000dca0  dirtree_recurse+120          external/toybox/lib/dirtree.c:156
  000000000000dbf4  dirtree_handle_callback+124  external/toybox/lib/dirtree.c:115
  0000000000036334  ps_main+952                  external/toybox/toys/posix/ps.c:1241
  00000000000139b0  toy_exec+92                  external/toybox/main.c:166
  0000000000013570  toybox_main+48               external/toybox/main.c:179
  0000000000013a74  main+120                     external/toybox/main.c:237
  00000000000a1e08  __libc_init+88               bionic/libc/bionic/libc_init_dynamic.cpp:124
  000000000000ccc0  _start_main+80               sfp-exceptions.c:?
```

**Comment by landley** [comment]
On 08/31/2017 03:11 PM, Elliott Hughes wrote:
> another instance today from automated testing:

Ok, I pushed an attempted fix.

The delay was that I wanted to create a test harness that spawns and
exits a lot of processes while ps or top repeatedly run, and try to
trigger the conditions of the failure (I.E. see the bug myself and then
maybe leave something running overnight to make sure it stays up), but
the _theory_ of what's happening is pretty clear so I can plug one more
hole in the meantime anyway.

Rob

**Comment by enh** [comment]
time to close this as fixed? haven't seen another instance in months since the last fix...
