### ISSUE TITLE
xargs -0 drops arguments

### ISSUE THREAD

**Issue by rprichard** [landley/toybox#78]
Actual output:
```
$ printf 'a\0b\0c\0d\0e\0f' | ~/toybox/toybox xargs -0 -n1 echo _
_ a
_ c
_ e
_

$ printf 'a\0b\0c\0d\0e\0f' | ~/toybox/toybox xargs -0 -n2 echo _
_ a b
_ d e
_

$ printf 'a\0b\0c\0d\0e\0f' | ~/toybox/toybox xargs -0 -n3 echo _
_ a b c
_ e f
```

Expected output:
```
$ printf 'a\0b\0c\0d\0e\0f' | xargs -0 -n1 echo _
_ a
_ b
_ c
_ d
_ e
_ f

$ printf 'a\0b\0c\0d\0e\0f' | xargs -0 -n2 echo _
_ a b
_ c d
_ e f

$ printf 'a\0b\0c\0d\0e\0f' | xargs -0 -n3 echo _
_ a b c
_ d e f
```

printf is working:
```
$ printf 'a\0b\0c\0d\0e\0f' | ~/toybox/toybox od -tx1
0000000 61 00 62 00 63 00 64 00 65 00 66
0000013
```

FWIW: I was using `xargs -0` to print `/proc/<pid>/cmdline`. It's also commonly used with `find -print0`.

**Comment by rprichard** [comment]
I also tried arguments larger than one character:
```
$ printf 'aa\0bb\0cc\0dd' | ~/toybox/toybox xargs -0 -n2 echo _
_ aa bb
_ dd
```

**Comment by enh** [comment]
suggested fix: http://lists.landley.net/pipermail/toybox-landley.net/2017-December/009319.html

in -0 mode when we hit the -n limit we were returning (char*)1, claiming that we'd used all the data, where in fact we hadn't, which led to us skipping that entry.

**Comment by enh** [comment]
fixed by https://github.com/landley/toybox/commit/70a6c55499eabf1229dfb0b49f08b366cbaa7896

can be closed
