### ISSUE TITLE
 compiling twrp latest for zte blade a610 fail

### ISSUE THREAD

**Issue by peturbg** [landley/toybox#79]
hi guys.

First i use toybox from lineage 14.1 and it comment microcom.c don't exist and after that i download latest microcom from android and i paste microcom.c to the correct dirrectory. when i make clean and after that make recoveryimage and get 30 min and xx sec. and it comment this is from make recoveryimage:

target  C: toybox_recovery <= external/toybox/toys/net/microcom.c
external/toybox/toys/net/microcom.c:47:28: error: use of undeclared identifier 'TT'
  tcsetattr(0, TCSAFLUSH, &TT.original_stdin_state);
                           ^
external/toybox/toys/net/microcom.c:48:13: error: use of undeclared identifier 'TT'
  tcsetattr(TT.fd, TCSAFLUSH, &TT.original_fd_state);
            ^
external/toybox/toys/net/microcom.c:48:32: error: use of undeclared identifier 'TT'
  tcsetattr(TT.fd, TCSAFLUSH, &TT.original_fd_state);
                               ^
external/toybox/toys/net/microcom.c:60:8: error: use of undeclared identifier 'TT'
  if (!TT.s) speed = 115200;
       ^
external/toybox/toys/net/microcom.c:61:21: error: use of undeclared identifier 'TT'
  else speed = atoi(TT.s);
                    ^
external/toybox/toys/net/microcom.c:65:63: error: use of undeclared identifier 'TT'
  if (i == ARRAY_LEN(speeds)) error_exit("unknown speed: %s", TT.s);
                                                              ^
external/toybox/toys/net/microcom.c:69:3: error: use of undeclared identifier 'TT'
  TT.fd = xopen(*toys.optargs, O_RDWR | O_NOCTTY | O_NDELAY);
  ^
external/toybox/toys/net/microcom.c:70:22: error: use of undeclared identifier 'TT'
  if (-1==(i = fcntl(TT.fd, F_GETFL, 0)) || fcntl(TT.fd, F_SETFL, i&~O_NDELAY))
                     ^
external/toybox/toys/net/microcom.c:70:51: error: use of undeclared identifier 'TT'
  if (-1==(i = fcntl(TT.fd, F_GETFL, 0)) || fcntl(TT.fd, F_SETFL, i&~O_NDELAY))
                                                  ^
external/toybox/toys/net/microcom.c:74:8: error: use of undeclared identifier 'TT'
  xraw(TT.fd, "fd", speed, &TT.original_fd_state);
       ^
external/toybox/toys/net/microcom.c:74:29: error: use of undeclared identifier 'TT'
  xraw(TT.fd, "fd", speed, &TT.original_fd_state);
                            ^
external/toybox/toys/net/microcom.c:75:24: error: use of undeclared identifier 'TT'
  xraw(0, "stdin", 0, &TT.original_stdin_state);
                       ^
external/toybox/toys/net/microcom.c:79:15: error: use of undeclared identifier 'TT'
  fds[0].fd = TT.fd;
              ^
external/toybox/toys/net/microcom.c:89:24: error: use of undeclared identifier 'TT'
      ssize_t n = read(TT.fd, buf, sizeof(buf));
                       ^
external/toybox/toys/net/microcom.c:97:29: error: use of undeclared identifier 'FLAG_X'
      if (!(toys.optflags & FLAG_X)) {
                            ^
external/toybox/toys/net/microcom.c:99:23: error: use of undeclared identifier 'TT'
          tcsendbreak(TT.fd, 0);
                      ^
external/toybox/toys/net/microcom.c:103:14: error: use of undeclared identifier 'TT'
      xwrite(TT.fd, buf, 1);
             ^
17 errors generated.
build/core/binary.mk:1087: recipe for target '/home/peturbg/BLADE/out/target/product/a610/obj/EXECUTABLES/toybox_recovery_intermediates/toys/net/microcom.o' failed
make: *** [/home/peturbg/BLADE/out/target/product/a610/obj/EXECUTABLES/toybox_recovery_intermediates/toys/net/microcom.o] Error 1

#### make failed to build some targets (30:20 (mm:ss)) ####

peturbg@workgroup:~/BLADE$ 

This is from Android.mk:

# TWRP stuff
RECOVERY_VARIANT := twrp
TW_THEME := portrait_hdpi
RECOVERY_GRAPHICS_USE_LINELENGTH := true
TW_NO_REBOOT_BOOTLOADER := true
TW_BRIGHTNESS_PATH := /sys/devices/platform/leds-mt65xx/leds/lcd-backlight/brightness
TARGET_USE_CUSTOM_LUN_FILE_PATH := /sys/devices/platform/mt_usb/musb-hdrc.0.auto/gadget/lun%d/file
TW_MAX_BRIGHTNESS := 255
TW_EXCLUDE_SUPERSU := true
TW_INCLUDE_FB2PNG := true
TW_NO_CPU_TEMP := true
TW_REBOOT_BOOTLOADER := true
TW_REBOOT_RECOVERY := true
TW_HAS_DOWNLOAD_MODE := true
TW_EXCLUDE_SUPERSU := true
TW_USE_TOOLBOX := true

TARGET_USE_CUSTOM_LUN_FILE_PATH := "/sys/devices/virtual/android_usb/android0/f_mass_storage/lun%d/file"

BOARD_SEPOLICY_DIRS := $(LOCAL_PATH)/sepolicy

# Use old sepolicy version
POLICYVERS := 29

# Seccomp filter
BOARD_SECCOMP_POLICY := $(LOCAL_PATH)/seccomp

**Comment by landley** [comment]
On 12/16/2017 12:56 PM, peturbg wrote:
> hi guys.
> 
> First i use toybox from lineage 14.1 and it comment microcom.c don't
> exist and after that i download latest microcom from android and i paste
> microcom.c to the correct dirrectory. when i make clean and after that
> make recoveryimage and get 30 min and xx sec. and it comment this is
> from make recoveryimage:
> 
> target C: toybox_recovery <= external/toybox/toys/net/microcom.c
> external/toybox/toys/net/microcom.c:47:28: error: use of undeclared
> identifier 'TT'
> tcsetattr(0, TCSAFLUSH, &TT.original_stdin_state);
> ^

It didn't rebuild the files in the generated/ directory to notice the
new command, so there's no #define for TT for that command. In theory
"make clean; make oldconfig" should do it, but I always do "make clean;
make defconfig"...

> build/core/binary.mk:1087: recipe for target
> '/home/peturbg/BLADE/out/target/product/a610/obj/EXECUTABLES/toybox_recovery_intermediates/toys/net/microcom.o'
> failed
> make: ***
> [/home/peturbg/BLADE/out/target/product/a610/obj/EXECUTABLES/toybox_recovery_intermediates/toys/net/microcom.o]
> Error 1
> 
> 
>         make failed to build some targets (30:20 (mm:ss))
> 
> peturbg@workgroup:~/BLADE$
> 
> This is from Android.mk:

The android guys manually update the generated/ files instead of running
the toybox make/make.sh. They have instructions on how to do that in
their makefile:

https://android.googlesource.com/platform/external/toybox/+/master/Android.mk#19

I should really tweak things so they can run the generator scripts each
build. It's on my todo list...

Rob

**Comment by peturbg** [comment]
hi are you the developer of toybox. man you have to speak with everybody in linux and android tell them they have to make everything autosolved. if error try start to comment exactly where is the error and how it can be solved. linux fail becouse there is no solutions. for example in linux there will be error in compile when it find : so to be solved in compile peoples need to put /: person who dont developer will not know and he can lost all him life to seek for solution. happy 23, 24 and 25 and happy new year

**Comment by peturbg** [comment]
I delete old toybox and i download repo sync. After that i move microcom.c in toys/net and i write make clean after that make defconfig and then i write make -j4 recoveryimage and it comment error:
twrp developers you need to make it automatically and when it fail to show how peoples need to solve it. 

es/lib/lib.P; sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\\\\$//' -e '/^\$/ d' -e 's/\$/ :/' < /home/peturbg/BLADE/out/target/product/a610/obj/EXECUTABLES/toybox_recovery_intermediates/lib/lib.d >> /home/peturbg/BLADE/out/target/product/a610/obj/EXECUTABLES/toybox_recovery_intermediates/lib/lib.P; rm -f /home/peturbg/BLADE/out/target/product/a610/obj/EXECUTABLES/toybox_recovery_intermediates/lib/lib.d )"
In file included from external/toybox/lib/lib.c:6:
external/toybox/toys.h:8:10: fatal error: 'generated/config.h' file not found
#include "generated/config.h"
         ^
1 error generated.
ninja: build stopped: subcommand failed.
build/core/ninja.mk:151: recipe for target 'ninja_wrapper' failed
make: *** [ninja_wrapper] Error 1

#### make failed to build some targets (04:29 (mm:ss)) ####

peturbg@workgroup:~/BLADE$

**Comment by peturbg** [comment]
when i move from android toybox to toys/net/microcom.c and start compile make recoveryimage it comment upper error. When i delete folder toybox and repo sync --force-sync it download the same toybox and when i compile it comment this error: 
build/core/base_rules.mk:320: warning: ignoring old commands for target `/home/peturbg/BLADE/out/target/product/a610/system/lib/libui_ext.so'
build/core/Makefile:34: warning: overriding commands for target `/home/peturbg/BLADE/out/target/product/a610/system/lib64/libui_ext.so'
build/core/base_rules.mk:320: warning: ignoring old commands for target `/home/peturbg/BLADE/out/target/product/a610/system/lib64/libui_ext.so'
Starting build with ninja
ninja: Entering directory `.'
ninja: error: 'external/toybox/toys/net/microcom.c', needed by '/home/peturbg/BLADE/out/target/product/a610/obj/EXECUTABLES/toybox_recovery_intermediates/toys/net/microcom.o', missing and no known rule to make it
build/core/ninja.mk:151: recipe for target 'ninja_wrapper' failed
make: *** [ninja_wrapper] Error 1

#### make failed to build some targets (01:15 (mm:ss)) ####

peturbg@workgroup:~/BLADE$ 

It error is know that micro... don't exist but there is not solution how peoples can solve it. if i move micro... to toy/net it comment error from the upper topic if i repo sync --force-sync it download working toybox but it don't contain micro... if this mean micro... don't exist. How toybox developers accept this. Make self solved toybox. Android manual it comment mm -j32 and it comment: mm -j32


Could not open packet


How it that google write on they official google forum peoples to use mm-32 and when mm -j32 it comment Could not open packet so google is writing false coomands.

**Comment by peturbg** [comment]
1

**Comment by landley** [comment]
On 12/17/2017 12:10 PM, peturbg wrote:
> I delete old toybox and i download repo sync. After that i move
> microcom.c in toys/net and i write make clean after that make defconfig
> and then i write make -j4 recoveryimage and it comment error:
> twrp developers you need to make it automatically and when it fail to
> show how peoples need to solve it.

You do realize you're giving orders to volunteers, right? (Also, this is
the first I've heard of twrp. They're a downstream consumer of the
Android Open Source Project build, which is both a consumer of and
significant contributor to my https://landley.net/toybox/about.html
project.)

> es/lib/lib.P; sed -e 's/#.///' -e 's/^[^:]/: *//' -e 's/ *\\$//' -e
> '/^$/ d' -e 's/$/ :/' <
> /home/peturbg/BLADE/out/target/product/a610/obj/EXECUTABLES/toybox_recovery_intermediates/lib/lib.d
>>>
> /home/peturbg/BLADE/out/target/product/a610/obj/EXECUTABLES/toybox_recovery_intermediates/lib/lib.P;
> rm -f
> /home/peturbg/BLADE/out/target/product/a610/obj/EXECUTABLES/toybox_recovery_intermediates/lib/lib.d
> )"
> In file included from external/toybox/lib/lib.c:6:
> external/toybox/toys.h:8:10: fatal error: 'generated/config.h' file not
> found
> #include "generated/config.h"
> ^
> 1 error generated.
> ninja: build stopped: subcommand failed.
> build/core/ninja.mk:151: recipe for target 'ninja_wrapper' failed
> make: *** [ninja_wrapper] Error 1

Android replaced the build system I wrote with a different one. Mine is
a set of bash scripts with a make wrapper. Ninja is the new build system
the android guys replaced make with. It looks like when you type "make"
your environment has a wrapper that calls ninja instead of make so it's
never calling my make/make.sh shell script.

Make is a posix command:
http://pubs.opengroup.org/onlinepubs/9699919799/utilities/make.html

Ninja is a new build tool that's about 5 years old:
https://en.wikipedia.org/wiki/Ninja_(build_system)

Files ending in .mk (such as Android.mk) are ninja files.

If you had an actual make binary, it would read the file "Makefile"
which would source kconfig/Makefile which does:

$ make defconfig
cc -o kconfig/conf kconfig/conf.c kconfig/zconf.tab.c -DKBUILD_NO_NLS=1\
		-DPROJECT_NAME=\"ToyBox\"
scripts/genconfig.sh
kconfig/conf -D /dev/null Config.in > /dev/null

You might try running those commands manually?

Rob

**Comment by peturbg** [comment]
be voluntaree or don't be voluntaree ARE SHITS.

Yes there are peoples who are insuted,first i had been insulted from this linux and android SHITS. I buy smarthphone more than 7xx $ and it come with android spy software, i don't pay for spy i don't want spy on my smartphone, second it uses linux SHITS linus torvalds DON'T want to solve KERNEL bugs from year 2013, and when BULGARIAN person solved kernel bug linus torvalds INSULT HIM. SO you solved, and you are insulted by linus torvalds. I will be glad linus torvalds read this email. linus torvals YOU ARE WORSE THAN SHITS. I had used linux for 1 years and i found VERY extreme bugs, debian, ubuntu, fedora and etc. DENIED TO REPAIR, SOLVED THEM. WHY I NEED TO spend 24 hours, 7 days and 365 days when developers don't want to SOLVE them. There is min. bug in nautilus when you open 2 windows and start copy it will close inmediatelly and if you have important stuff they are lost, this is min. and this BUG exist from long time ago. All new updates don't repair old updates, all new updates creates new PROBLEMS AND MUCH BIG PROBLEMS. There can be auto solved linux but they don't want. There can be old and new support but they don't want. Peoples don't buy smartphones becouse you are screwed And no i'm not bulgarian. So linux is worse operation system that exist, with every new updates they create new big problems, min. in compile : it get error, if you don't know solve: write /: so this stupid women who make this : she has to think when make : to can be compiling and don't get problems. IN linux you can lost your life, to compile 9 mb. or 30 mb. when you compile more MB more times you are gonna lost in your life. In windows you can install 9 mb. for less than 1 min. in linux you compile 9 mb. but it repeat the compile proces 2 times and if first time it don't give you error on the second repeat it will give you error, if you don't know how to repair second repeat error then you can't start programs. This mean, if you compile 9 mb. and it get 10 min. and second compile will get 10 min. so this is 20 min. lost in your life, and if error occure then you are screwed. And yes ninja make plus, plus and more plus. make is slow and insecure, ninja is fast.  ninja can be 5 years old but it is better. In ninja you can see how it is gonna compile in make you don't know what is total. This is dissadvantatge. make is dissadvantatge, make can be better from ninja but developers are closed.

In linux you don't know if files are linked, hard linked or low linked, if you copy linked files it will stop work and you will not know from what directory they are comming. In windows if you copy file you copy file. In linux when ubuntu start maybe from version 9 " ubuntu women developers comment. We will make ubuntu support all KIND OF COMPUTERS " THIS IS LIFE. in ubuntu 17.10 you have to have min. 1 gb. or 2 gb. of ram to install it. in ubuntu iso image it is 2 gb. and before it was 690 mb. ubuntu had put spy programs, ubuntu in start was free. in linux and android it start SElinux that was created by nsa " national security agency " we all know they are SHITS who want to KILL ALL HUMANKIND. SPYING AND KILLING INNOCENT PEOPLES. LOOK WHAT usa has converted IRAN, IRAQ and continuosly try to kill Africa and etc. linus tarvall accepted selinux becouse they give him money. linus torvall is not free. So i stop use linux and android. If you peoples 

make defconfig will not make config.g config.g will make it make oldconfig. PEOPLES there can be support for your device but linux and android don't want you to have latest operation systems becouse THEY WILL LOST MONEY. in linux like i do you can enter in other peoples system and use they operation systems linux will not solve it. ALL PEOPLES who don't use android 8 are problems with WPA security. they comment windows is insecure but linux is more insecure than windows when i enter more than 2 computers and use they ip. jajajaja voluntarees and don't voluntarees. So long jimmy continue belive in voluntaree and don't voluntaree becouse they pay them money. In hungary soro had PAY illegaly money so peoples try SABOTAGE the country, soro didn't make it. guys don't use linux, android and windows.

**Comment by StarMariner** [comment]
Merry Christmas Everyone, Love to all. I read the 1st 2 lines and then gave up. Best wishes to all those hard working volunteers. I look up to you , thanks maties :)
