### ISSUE TITLE
http://landley.net/toybox/downloads/toybox-0.7.5.tar.gz is version 0.7.4

### ISSUE THREAD

**Issue by peturbg** [landley/toybox#80]
rob in http://landley.net/toybox/downloads/toybox-0.7.5.tar.gz
it comment this is version 0.7.4
/* Toybox infrastructure.
 *
 * Copyright 2006 Rob Landley <rob@landley.net>
 */

#include "toys.h"

#ifndef TOYBOX_VERSION
#define TOYBOX_VERSION "0.7.4"
#endif

**Comment by landley** [comment]
http://lists.landley.net/pipermail/toybox-landley.net/2017-October/009205.html
