### ISSUE TITLE
toysh segfaults after "clear" or "reset"

### ISSUE THREAD

**Issue by reverendhomer** [landley/toybox#83]
Hi,

playing with toybox I've found that any command after "clear" or "reset" causes "Double free or corruption". Simple test for this is
```bash
echo -e 'clear\nuname -a' | toybox sh
echo -e 'reset\nuname -a' | toybox sh
```

You can also reproduce this in interactive mode.

Tested with `0.7.4-21-g105595524ead` and  `0.7.5-58-g1fec45a2a57f`

**Comment by reverendhomer** [comment]
Also I cannot test it via '-c' flag. ` ./toybox sh -c 'clear; ls'` causes `sh: exec clear;: No such file or directory` and `./toybox sh -c 'clear && ls'` hangs my terminal.

**Comment by enh-google** [comment]
works for me at ToT (but toysh is still in pending, so the usual warnings apply...).
