### ISSUE TITLE
Make zlib functions compatible with miniz

### ISSUE THREAD

**Issue by tpimh** [landley/toybox#84]
[miniz](https://github.com/richgel999/miniz) is a small implementation of zlib, it tries to be compatible with zlib, but it's not 100% compatible.

It lacks `gzFile`. I think `toys/pending/gzip.c` should be rewritten to be compatible with miniz.

**Comment by landley** [comment]
On 03/06/2018 04:48 AM, Twisted Pair in my Hair wrote:
> miniz <https://github.com/richgel999/miniz> is a small implementation of zlib,
> it tries to be compatible with zlib, but it's not 100% compatible.
> 
> It lacks |gzFile|. I think |toys/pending/gzip.c| should be rewritten to be
> compatible with miniz.
Not a fan of miniz. That's one of the inflate/deflate implementations I looked
at before writing my own decompressor. (Over the years I've read through
info-zip, busybox's fork of zlib, like 3 other forks of zlib... I almost merged
"flate" at one point (https://landley.net/notes-2014.html#30-01-2014) but
changed my mind (https://landley.net/notes-2014.html#04-02-2014 and then
https://landley.net/notes-2014.html#05-02-2014)...)

If I recall my objection to miniz was it's a giant hairball of nested macros
that minimizes source code line count, but not in the service of size, speed, or
readability. Just code golf.

Rob
