### ISSUE TITLE
`cp -p` does not preserve timestamps

### ISSUE THREAD

**Issue by SebiderSushi** [landley/toybox#88]
In toybox version 0.7.1-android and in toybox version 0.7.5 for x86_64 files copied with `cp -p` have their copy time set to all timestamps. However when using `cp --preserve=t` timestamps are as expected.

**Comment by Rikk** [comment]
Fixed in https://github.com/landley/toybox/commit/b6427f1bfe7291d6dcb102660685a2fc3bfc5123

**Comment by SebiderSushi** [comment]
Thanks for your note!
